### ISSUE TITLE
Questions: Disk usage and network connection

### ISSUE THREAD

**Issue by schmunk42** [docker-library/docker#1]
Sorry if the repo is not ready for public consumption yet, but I'd have two burning questions.

1. Does this address https://github.com/jpetazzo/dind#important-warning-about-disk-usage and is /var/lib/docker reused from the "outer-docker"?
2. How to connect to the containers running in the container?

PS: I tried a build and ran a nginx container, which worked quite well so far.

**Comment by tianon** [comment]
Yeah, definitely not ready for public consumption yet.  Really only created it to start soliciting comments from people who've expressed interest in it being a thing, such as @jpetazzo and @jfrazelle.

Functionally, it probably has all the exact same shortcomings as `jpetazzo/dind`.
