### ISSUE TITLE
mtu in dind doesn't seem to have an affect

### ISSUE THREAD

**Issue by neclimdul** [docker-library/docker#102]
I'm having trouble running dind in k8s and it seems to be related to mtu settings. I'm trying to control the mtu on the docker bridge as it seems to resolve the issue but none of the documented methods seem to work. 

Using the `docker:dind` and `docker:stable-dind` containers.

```
/ # cat /etc/docker/daemon.json
{"mtu": 1450}
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if61: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 0a:58:0a:f4:01:2f brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.47/24 scope global eth0
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:41:2d:55:80 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```
I've tried setting the daemon.json config and passing the argument directly and neither seems to have an effect.

In reality setting either of this for a container can be tricky and a environment variable would make things a lot easier but that seems like another issue.

**Comment by tianon** [comment]
Does this setting still work properly on a non-dind instance of `dockerd`?

(If there's an issue here, I don't think it's one specific to this image and/or something we could fix in the image -- it's likely either a limitation of the kernel itself, or a bug/feature in Docker itself.)

**Comment by neclimdul** [comment]
Just tried doing the same thing on my local machine(ubuntu 17.10) and both the config and argument did not affect the mtu of the bridge it created. I made sure to delete the bridge between each test to ensure docker was creating it and not just leaving the existing interface as well.

**Comment by neclimdul** [comment]
Opened an issue on moby so I guess I'll close this for now.
