### ISSUE TITLE
Error running latest docker image

### ISSUE THREAD

**Issue by antondalgren** [docker-library/docker#106]
Hi!

My CI pipeline tries to pull the latest docker image available on dockerhub and run it. I just got the following error message:

'ERROR: Preparation failed: no matching manifest for linux/amd64 in the manifest list entries' 

Could this be related to a new release just got pushed ~15 mins ago?

**Comment by turbo** [comment]
I can repro this on any linux machine:

```text
docker pull docker:latest
latest: Pulling from library/docker
no matching manifest for linux/amd64 in the manifest list entries
```

It is also breaking all CI jobs for us. E.g.:

```text
Running with gitlab-runner 10.6.0 (a3543a27)
  on docker-auto-scale 72989761
Using Docker executor with image docker:latest ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image sha256:6fc95ba0a7762a13d4db830df765c534ece1963f11093dfb8940f525b63084c3 for docker:dind ...
Waiting for services to be up and running...
Pulling docker image docker:latest ...
ERROR: Preparation failed: Error: No such image: docker:latest
Will be retried in 3s ...
Using Docker executor with image docker:latest ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image sha256:6fc95ba0a7762a13d4db830df765c534ece1963f11093dfb8940f525b63084c3 for docker:dind ...
Waiting for services to be up and running...
Pulling docker image docker:latest ...
ERROR: Preparation failed: Error: No such image: docker:latest
Will be retried in 3s ...
Using Docker executor with image docker:latest ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image sha256:6fc95ba0a7762a13d4db830df765c534ece1963f11093dfb8940f525b63084c3 for docker:dind ...
Waiting for services to be up and running...
Pulling docker image docker:latest ...
ERROR: Preparation failed: Error: No such image: docker:latest
Will be retried in 3s ...
ERROR: Job failed (system failure): Error: No such image: docker:latest
```

**Comment by paulRbr** [comment]
Same for us. I think the latest image news to be pushed again to the docker hub. Not sure who we should ping for that as it will probably affect a lot of people. @tianon maybe, can you help please?

**Comment by turbo** [comment]
`docker:stable` still works though.

**Comment by kachkaev** [comment]
ping @psftw @yosifkit 😨

**Comment by stvndall** [comment]
I'm having the same issue on gitlab builds trying to pull docker:latest.
is it a good standard to use :stable in general?

**Comment by paulRbr** [comment]
@stvndall it completely if the tag is available for the docker image you are using it will most probably be much more reliable. @turbo 's message in this thread (https://github.com/docker-library/docker/issues/106#issuecomment-380738199) is the best solution to the initial problem.

If you want a stable usage of the `docker` image: **use the `stable` tag**
If you want a development/unstable version of the `docker` image: _use the `latest` tag_

**Comment by stvndall** [comment]
thanks, I'll use stable where required.

**Comment by rhefner1** [comment]
@stvndall @paulRbr This is good advice but for me, it doesn't change the fact that the `:latest` tag is still littered throughout my company and any CI build depending on it is broken. 

To the maintainers: the `:latest` image isn't *broken* per se, but it is just plain missing. As you see above: `no matching manifest for linux/amd64 in the manifest list entries`.

**Comment by prvak** [comment]
It seems similar to this problem: https://github.com/docker-library/official-images/issues/3835

**Comment by kachkaev** [comment]
I was able to `docker pull docker` just now 🎉

**Comment by tianon** [comment]
Yep, this was definitely a case of https://github.com/docker-library/official-images/issues/3835. :+1:
