### ISSUE TITLE
discuss: dind-git variant

### ISSUE THREAD

**Issue by thurt** [docker-library/docker#109]
> @tianon: I'd be willing to consider a **docker:dind-git variant**, but I'm still **dubious of the value** [ref: #68]

Here is the value I see:

there are some docker images that are intended to be run as a one-off build process. for example,
```
docker run \
  --rm \
  --mount type=bind,src=$PWD,dst=/local \
  swaggerapi/swagger-codegen-cli generate -i https://url.to.definition.file -l typescript-fetch -o /local
```
that will create/update some files in `PWD` where `PWD` represents a git repo. So the value of a dind-git variant comes from the fact that I can clone the git repo, run the build process, and push changes back to the git remote from a single container.

Compare that to having a dind container and a separate git client container: in this case `PWD` represents a path on the docker host not the git client container. so I will have to volume mount `PWD` in such a way that it represents the same directory path on both docker host container and git client container in order to maintain a semblance of isolation. 

A separate git client container is usually fine for workflows involving `docker build` because that command sends a context of files, but `docker run` does not. 

Please correct me if any of these details are wrong but this is where I'm at

**Comment by tianon** [comment]
I'm not sure I understand what it is you're trying to do.  Are you building Docker images from within a Docker container?

**Comment by thurt** [comment]
forgive me, i think i figured out a better way for my scenario that doesn't need a dind-git variant. 


Here's some more detail:
I use a development container as my IDE which is connected to the docker daemon via a docker socket. My main issue stemmed from `docker run` when I try to bind mount src=$PWD it will try to use that path on the dockerhost when I want it to use the path on the development container. 

One thing I did not realize is `docker cp` is aware of what container I am running the command from. This is in contrast to `docker run`, which always uses paths from the dockerhost.

you can see what i figured out in this rough makefile recipe with dind:
```bash
    docker run \
        --name=docker \
        -d \
        -it \
        --privileged \         
        --mount type=volume,src=dind-volume,dst=/var/lib/docker \
        docker:dind --group 999
    #copy in the files needed
    docker cp ./cms/cms.swagger.json docker:/cms.swagger.json
    docker cp ../cms-client-api docker:/cms-client-api
    #setup/run the build container
    docker exec -it docker sh -c "docker pull swaggerapi/swagger-codegen-cli:v2.3.1"
    docker exec -it docker sh -c "docker run --rm --mount type=bind,src=/cms-client-api,dst=/local --mount type=bind,src=/cms.swagger.json,dst=/cms.swagger.json swaggerapi/swagger-codegen-cli:v2.3.1 generate -i /cms.swagger.json -l typescript-fetch -o /local"
    #copy out the modified repo
    docker cp docker:/cms-client-api ../
    docker stop docker && docker rm docker
```
