### ISSUE TITLE
dind not working if pulling from local registry

### ISSUE THREAD

**Issue by santosh0705** [docker-library/docker#11]
I'm using `docker:dind` in GitLab CI. Its working fine if the image for the service is tagged from official registry.
If I tag it to local registry and push it and next I use it for service image its not working.

I'm testing on this project:
https://gitlab.com/gitlab-examples/docker

pls check this exact issue with gitlab-ci: https://gitlab.com/gitlab-examples/docker/issues/2

**Comment by santosh0705** [comment]
Found the problem, its related to linking alias. GitLab runner create alias other than `docker` the build container created from `docker:latest` or `docker:git` depends on the alias. It only works if alias is `docker`.

I've described the problem here: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1375

Is there any plan to work on dynamically discovering the service?

**Comment by tianon** [comment]
No plans to dynamically discover the service, but you should be fine to set `DOCKER_HOST` yourself; see https://github.com/docker-library/docker/blob/fdd9cb04d92a35aa136ce3e7be5daf3f13adcb29/17.03/docker-entrypoint.sh#L17 for where we set this when we detect a `docker` link.

For example, if you can access your Docker daemon container via a DNS lookup of `some-docker-instance`, you'd set `-e DOCKER_HOST='tcp://some-docker-instance:2375'` on your Docker client container. :+1:

(Sorry for the massive delay in response! :disappointed:)
