### ISSUE TITLE
Use systemd-resolve

### ISSUE THREAD

**Issue by runephilosof** [docker-library/docker#114]
On AWS EC2 with an Ubuntu 18.04 the `/etc/resolv.conf` looks similar to:
```
:~$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.53
search eu-west-1.compute.internal
```

Running `systemd-resolve --status` gives:
```
:~$ systemd-resolve --status
Global
         DNS Servers: 172.30.0.2
...more...
```

When I create a docker container and queries dns it goes directly to 8.8.8.8. Instead, it should use the same dns server as the host.
If I edit the `/etc/resolv.conf` on the host to contain `nameserver 172.30.0.2`, it starts working as expected.
Docker should recognize this by itself.

**Comment by wglambert** [comment]
You could mount the file

```console
docker run --rm -dit -v /etc/resolv.conf:/etc/resolv.conf:ro --name ubuntu ubuntu:18.04
docker exec -it ubuntu bash

root@9b3ab686d79f:/# cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 172.30.0.2
nameserver 8.8.4.4
```

If you want to make a request for this feature try https://github.com/docker as these repos are all for official-images, and this `docker` repo is for docker-in-docker for development of docker

**Comment by runephilosof** [comment]
Sorry. I have created the issue in https://github.com/docker/for-linux instead
