### ISSUE TITLE
Error when build image: error checking context: 'no permission to read from '/proc/1/mem''.

### ISSUE THREAD

**Issue by Just4test** [docker-library/docker#115]
I want to build Image in docker, but get an error. I run this on Mac.

> just4test$ docker run --privileged --name some-docker -d docker:stable-dind
> 9da2c7e017477c60398386ca5e8ff62ccaeb22c7cf2452c42ada2ddd167ac349
> just4test$ docker run --rm --link some-docker:docker -ti docker:edge sh
> / # echo from docker > Dockerfile
> / # docker build .
> error checking context: 'no permission to read from '/proc/1/mem''.

I also try to map /var/run/docker.sock into docker and get the same error.

Here's the docker info and version of docker edge which linked to dind.
> / # docker info
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 18.03.1-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.9.87-linuxkit-aufs
> Operating System: Alpine Linux v3.7 (containerized)
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 1.952GiB
> Name: 9da2c7e01747
> ID: WJVB:IWIP:Z42I:7CVN:YPSY:3AGT:E4MY:JOTE:W5IQ:2FNG:QIPC:QKII
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled

> / # docker version
> Client:
>  Version:      18.05.0-ce
>  API version:  1.37
>  Go version:   go1.9.2
>  Git commit:   f150324
>  Built:        Wed May  9 22:11:29 2018
>  OS/Arch:      linux/amd64
>  Experimental: false
>  Orchestrator: swarm
> 
> Server:
>  Engine:
>   Version:      18.03.1-ce
>   API version:  1.37 (minimum version 1.12)
>   Go version:   go1.9.5
>   Git commit:   9ee9f40
>   Built:        Thu Apr 26 07:23:03 2018
>   OS/Arch:      linux/amd64
>   Experimental: false

**Comment by wglambert** [comment]
Are you able to build it outside of the dind environment

Without the Dockerfile I'm unable to try to reproduce

**Comment by Just4test** [comment]
Thank you! It solved my problem.

In the Dockerfile reference webpage: https://docs.docker.com/engine/reference/builder/#usage
> Warning: Do not use your root directory, /, as the PATH as it causes the build to transfer the entire contents of your hard drive to the Docker daemon.
