### ISSUE TITLE
What are the security implications of using Docker in Docker (dind)

### ISSUE THREAD

**Issue by norpol** [docker-library/docker#116]
Dear everyone,

I'm really curious* about the security implications of running Docker in Docker via. a forwarded Docker socket. So far I couldn't find any official documentation on this issue and I'm confused whether or not you can secure/filter access to the Docker socket at all.

\* I think it's not advisable to run Docker in Docker in any CI related environment, because it's insecure. I can only see that it's useful for development purposes.

In ideal case you could either point me to some official documentation or we get something into the official documentation.

At the moment it feels like untrained people might easily introduce a huge security issue into their CI/CDs (for example GitLab even [recommends setting it up](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor) for one of [their features](https://docs.gitlab.com/ee/ci/examples/code_climate.html)), without giving them the opportunity to understand the implications properly, because a of the discourse is "talking around this topic".

### [Don't expose the Docker socket (not even to a container)](https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html#)

Is an article that demonstrates straight forward privilege escalation via. a forwarded Docker socket.

### [~jpetazzo/Using Docker-in-Docker for your CI or testing environment? Think twice.](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

States in the introduction:
> The primary purpose of Docker-in-Docker was to help with the development of Docker itself. Many people use it to run CI (e.g. with Jenkins), which seems fine at first, but they run into many “interesting” problems that can be avoided by bind-mounting the Docker socket into your Jenkins container instead.
 
Which only address the topic implicitly and then starts to confusing by suggesting to bind-mount Docker socket into a container. I suppose that means for people running Jenkins already in a container to give Jenkins this capability instead.

Also:
- Doesn't mention anything about security implications
- Only tells that SELinux and other Linux Security Modules can cause operational problems
- Links to the initial commit of [`-insecure`](https://github.com/moby/moby/commit/280901e5fbd0c2dabd14d7a9b69a073f6e8f87e4) flag, which removes the Linux [capability whitelist](https://docs.docker.com/engine/security/security/#linux-kernel-capabilities), which appears to be the major security feature of Docker
- Links to [jpetazzo/dind](https://github.com/jpetazzo/dind), which doesn't mention anything about security

### Docker on [Docker Hub](https://hub.docker.com/_/docker/)

States at "What is Docker in Docker?"
> Although running Docker inside Docker is generally not recommended, there are some legitimate use cases, such as development of Docker itself.

Could add also the reasons why Docker inside Docker isn't recommended. I don't see why the link to ~jpetazzo's article, makes this clear.

### [Protect the Docker daemon socket](https://docs.docker.com/engine/security/https/)

Isn't talking about  protecting the socket, but how to setup certificates to access to a daemon socket via. HTTPS.

**Comment by tianon** [comment]
This is interesting information, but I'm not sure it's relevant as an issue on this repository.  I'd suggest trying [the Docker Community Forums](https://forums.docker.com/) or [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) to get more discussion going around this.

To be clear, I think it's a useful topic to discuss, but this is definitely not the appropriate forum to do so. :+1:

**Comment by norpol** [comment]
Might do, thanks for responding at all.
