### ISSUE TITLE
how to start docker in alpine without 'service docker start'  & 'rc-update add docker boot'

### ISSUE THREAD

**Issue by kenliang18** [docker-library/docker#118]
Dear all,
I have an issue that after I pull docker from internet,I find out I can't start the docker because it turns out error when I type 'service docker start'  or 'rc-update add docker boot'.As there is no related command within the alpine system.So,how can I start the docker service without those two commands offered?

**Comment by wglambert** [comment]
The [docs](https://github.com/docker-library/docs/tree/master/docker) for each image provides information for running the image. For DIND there is a video that gives the commands https://asciinema.org/a/24707

```console
$ docker run -it --privileged --name some-docker -d docker:dind
7f4547f661892f6c8cc3cde262f56128b59ee4c2600671b68dc2db5a6178aa8e
$ docker exec -it some-docker ash
/ # docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
/ # 
```

**Comment by kenliang18** [comment]
Thanks a lot.But how could I start the docker service when I pull docker:latest instead of docker:dind?
After I pull docker:latest,I find out when I type 'docker version' in the container,the system prints out only the version of the docker client without showing that of the docker server,unlike docker:dind showing both the information.

**Comment by wglambert** [comment]
You can do `dockerd &` and then ctrl+c to stop it from outputting to terminal. Requires `--privileged`
