### ISSUE TITLE
request: nightly dind image

### ISSUE THREAD

**Issue by AkihiroSuda** [docker-library/docker#125]
@tianon ^^

**Comment by yosifkit** [comment]
Similar issues: https://github.com/docker-library/official-images/issues/1281, https://github.com/rust-lang-nursery/docker-rust/issues/5

**Comment by tianon** [comment]
Yeah, _nightly_ builds aren't really feasible via the official images, but I do maintain https://hub.docker.com/r/tianon/docker-master/ which sources from https://master.dockerproject.org/ and should match this image's usage.

**Comment by AkihiroSuda** [comment]
thanks!
