### ISSUE TITLE
Is there any methods to disable EXPOSE 2375 port?

### ISSUE THREAD

**Issue by mapleeit** [docker-library/docker#136]
> This image includes EXPOSE 2375 (the Docker port), so standard container linking will make it automatically available to the linked containers (as the following examples illustrate).

I saw this paragraph at [https://hub.docker.com/_/docker/](https://hub.docker.com/_/docker/). I can understand the reason why expose 2375 port by default (use `--link` to link another container). 

**But**

1. it seems the `--link` param is deprecated now. https://docs.docker.com/network/links/

  ![image](https://user-images.githubusercontent.com/4194287/49708841-4d660800-fc6c-11e8-92f6-16801e9f0a0b.png)

2. In some cases, it is so awkward. Here is my case: I use `--network host` to start my dind container. I can only start one dind container because `0.0.0.0:2375` already in use by the first dind container.

**So should we remove the port exposure or provide another version without exposing port?**

**Comment by tao12345666333** [comment]
1. we shouldn't remove the expose port. because it must expose port to let other containers connect to it.

2. we can use other Network mode, not only `--link`.

3. if you use `--network host` , the published ports will be discard.

4. you can use `--host` to set some other ports.

**Comment by mapleeit** [comment]
> if you use --network host , the published ports will be discard.

I used `--network host`, but the published ports are still there:

```
docker run --rm --network host --name test --privileged docker:dind --iptables=false --bridge="none"
```

output:

```
time="2018-12-10T06:58:59.467995925Z" level=info msg="API listen on [::]:2375"
time="2018-12-10T06:58:59.468031721Z" level=info msg="API listen on /var/run/docker.sock"
```

---

And if I use `--network host`, actually I don't want to specify ports, instead I share the `docker.sock` to communicate.

**Comment by mapleeit** [comment]
I wonder that is there an option which I can use to avoid open some port. I have tried `--host="none"`, but it seems helpless.

**Comment by mapleeit** [comment]
> what do you want to do with dind ？

Building some CI tools. 
> and why use host network？

Because the security department removes the NAT module for some "security reason". I know that sucks 😞 

---

I looked into the `dockerd-entrypoint.sh`, and `docker run docker:dind dockerd --host="some host"` did resolve my problems, this will emit the default 2 hosts options. I miss the `dockerd` before.

Thanks a lot and sorry to interrupt. I'll close this.
