### ISSUE TITLE
Invalid Argument Error when mounting volume

### ISSUE THREAD

**Issue by rmb938** [docker-library/docker#14]
If I run dind with a host volume mount it errors out with invalid argument:

```
docker run -dit --privileged --volume=/Users/rmb938/dindvar:/var/lib/docker --name some-docker docker:dind
```
Then running docker logs shows:

```
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\
INFO[0000] New containerd process, pid: 20

FATA[0001] Error starting daemon: invalid argument
```

Yet without the volume mount it works perfectly fine.

**Comment by tianon** [comment]
Are you on OS X by chance?  (guessing based on `/Users/rmb938/dindvar`)

If so, mounting via vboxsf with docker-machine will _definitely_ not work here, and I really doubt that the shared file system in Docker for Mac is going to work much better.

Docker's `/var/lib/docker` directory needs to be able to support a number of things that most of these shared filesystems simply cannot provide, CoW being one of the primary ones (although with VFS it might be possible, although slow enough to make it likely unusable for much).

**Comment by rmb938** [comment]
I am using OSX and that makes sense. I'll figure out something else then.

Thanks :)

**Comment by tianon** [comment]
:+1:
