### ISSUE TITLE
How is the proxy for docker pull configured in the dind container?

### ISSUE THREAD

**Issue by jbrekelmans** [docker-library/docker#140]
How is the proxy for docker pull configured in the dind container?

I have tried setting HTTP_PROXY, HTTPS_PROXY and NO_PROXY (and their lowercase equivalents, but they do not seem to be picked up by the daemon).

**Comment by tianon** [comment]
From what I can find (for example, https://docs.docker.com/config/daemon/systemd/#httphttps-proxy), the environment variables you've listed should be correct. :confused:

There is likely something to https://docs.docker.com/network/proxy/ too -- perhaps the client needs the variables set appropriately as well?

**Comment by jbrekelmans** [comment]
Thanks for your reply Tianon.

Turns out our proxy was blocking certain host names, causing a timeout when pulling. But it worked when using different host names.

So `HTTP_PROXY` and `HTTPS_PROXY` (and their lowercase equivalents) correctly configure a docker pull/push proxy on the docker-in-docker container.
