### ISSUE TITLE
docker with debian base?

### ISSUE THREAD

**Issue by vsoch** [docker-library/docker#146]
hey @tianon ! Is there a tag (or do you know of another base) that has docker on top of some debian flavor? Thanks in advance for your help!

**Comment by vsoch** [comment]
In the meantime I'll build using alpine, anticipating that we don't have debian :)

**Comment by tianon** [comment]
I mean, I've got https://hub.docker.com/r/tianon/docker-tianon and https://hub.docker.com/r/tianon/docker-master, which are both Debian-based (the former is based on https://github.com/tianon/docker-deb-vendored, the latter is based on builds from https://master.dockerproject.org/).

If that's not good enough, it wouldn't be terribly hard to convert the relevant steps outlined in https://ram.tianon.xyz/post/2017/05/18/docker-setup-redux.html into a simple `Dockerfile`. :smile:

Any particular reason the base of the Docker-in-Docker image actually matters?  Wouldn't you be using it "remotely" and thus not even know or care what OS it's running on?

**Comment by vsoch** [comment]
I want to build R into it (as a base image for interacting with Docker and building shiny images) but Rcpp has [issues compiling on alpine](https://github.com/RcppCore/Rcpp/issues/448) so I can either fight with that, or go for a debian base that (most R images, e.g., if you look at the [rocker family](http://hub.docker.com/r/rocker)) are known to work with.

`tianon/docker-tianon` looks perfecto! Thanks for the quick response!

**Comment by tianon** [comment]
So that sounds like you just need the Docker _client_, not the daemon, right?

So you might actually be better/simpler with something like:

```dockerfile
FROM debian:stretch-slim
COPY --from=docker:18.09.3 /usr/local/bin/docker /usr/local/bin/
RUN docker --version
```

(Since the binaries we include / pull down from https://download.docker.com are static.)

**Comment by tianon** [comment]
Alternatively, you could simply download the static client binary directly from https://download.docker.com/ yourself (if you don't like `COPY --from=xxx`, which I'd totally understand since I don't love it myself, although I think it's an interesting idea for composing images).

**Comment by vsoch** [comment]
Oh that's a great idea! I'll give it a go. Thanks @tianon :)

**Comment by vsoch** [comment]
Turns out I [did need the daemon!](https://github.com/vsoch/docker-rize/blob/master/Dockerfile)

But all [worked out](https://circleci.com/orbs/registry/orb/vanessa/rize) in the end, thanks again!
