### ISSUE TITLE
docker 1.12 not pushed to dockerhub

### ISSUE THREAD

**Issue by w0mbat** [docker-library/docker#15]
Although the docker 1.12 GA files were commitet, the final images are not available from dockerhub - 1.12.0, 1.12.0-dind and 1.12.0-git need to be pushed

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check the "library/docker" manifest file in the docker-library/official-images repo, especially PRs with the "library/docker" label on that repo. 

It'll be going up with https://github.com/docker-library/official-images/pull/2005

**Comment by w0mbat** [comment]
thanks!
