### ISSUE TITLE
Why no 18.09-ce tag?

### ISSUE THREAD

**Issue by csandanov** [docker-library/docker#158]
Couldn't find any info why 18.09 tags have no ce, or are they all ce now?

**Comment by tianon** [comment]
See https://github.com/docker/docker-ce/releases/tag/v18.09.0, especially under "Packaging" (https://github.com/docker/docker-ce-packaging/pull/206).

See also https://github.com/docker-library/docker/commit/95b8a164cdcc520ec9466ac6b70f525a382f76ee for where we had to adapt to this upstream change between 18.09.0-ce-beta1 and 18.09.0-beta3. :smile:

**Comment by csandanov** [comment]
ok, so it was a pain dealing with these suffixes in semver comparison and it's not like we'll see `-ee` publicly available on docker hub
