### ISSUE TITLE
Is it planned to release a alpine 3.10 based docker image?

### ISSUE THREAD

**Issue by Colin-b** [docker-library/docker#159]
Looking at Dockerfile all I can see is alpine 3.9 and alpine 3.10 is available :)

Thanks again

**Comment by J0WI** [comment]
Feel free to open a PR :wink:

**Comment by tianon** [comment]
> alpine 3.10 is available

:smile:

Timestamp on this issue: 2019-06-20 at 2:29am PDT
Timestamp of https://github.com/docker-library/official-images/pull/6121 merging: 2019-06-19 at 1:11pm PDT

(See https://github.com/docker-library/docker/pull/161 for the PR @J0WI already opened :+1:)
