### ISSUE TITLE
18.09 image isn't forward compatible with 18.06

### ISSUE THREAD

**Issue by szymonpk** [docker-library/docker#162]
I am not sure if I should report it here or to busybox itself

```
$ docker run -it docker:18.06 /bin/sh
/ # timeout
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: timeout [-t SECS] [-s SIG] PROG ARGS
```

```
$ docker run -it docker:18.09 /bin/sh
/ # timeout
BusyBox v1.30.1 (2019-06-12 17:51:55 UTC) multi-call binary.

Usage: timeout [-s SIG] SECS PROG ARGS
```

Notice `-t` argument. they dropped it, and it is positional now. Is there any chance this can be reverted?

**Comment by wglambert** [comment]
This isn't really something we can change in the image, so you'd want to look upstream for information on this. 
The inclusion of BusyBox in the image is from Alpine, so aside from using an older version of Alpine there isn't anything we can change in the Dockerfile

I didn't see anything related to `timeout` in https://busybox.net or https://git.busybox.net/buildroot/tree/CHANGES

**Comment by szymonpk** [comment]
I found it, it is [an attempt to make timeout compatible with coreutils](https://github.com/mirror/busybox/commit/c9720a761e88e83265b4d75808533cdfbc66075b). I am not big fan of breaking changes on minor version bump, but I think we cannot do much about this :/ Thanks @wglambert.
