### ISSUE TITLE
latest 'dind' tag (19.03) gives error on Gitlab CI "failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?"

### ISSUE THREAD

**Issue by daenny** [docker-library/docker#170]
We are running a gitlab server and several gitlab-ci-runners. Today we woke up to several failed builds. 
We did several tests and we found out that the most likely culprits are the newest tags of the `docker:dind` and `docker:git` images. 
We tested with `docker:18-dind`  and `docker:18-git` and the errors does not occur anymore. 

The error is given below:
> time="2019-07-23T06:52:31Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial tcp 172.17.0.3:2375: connect: connection refused"

The gitlab-runners are running in privileged mode. 

EDIT: This is not a bug or unresolved issue:
see: https://github.com/docker-library/docker/issues/170#issuecomment-514366149

**Comment by RuriRyan** [comment]
I guess we have the same issue.

Errors by the actual docker:stable-dind iamge:

```bash
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
```

**Comment by jubel-han** [comment]
We are facing the same issue, It seems that docker daemon is listening on `2376` instead of `2375`

```
INFO[2019-07-23T07:30:10.485681000Z] Docker daemon                                 commit=aeac9490dc graphdriver(s)=overlay2 version=19.03.0
INFO[2019-07-23T07:30:10.486308400Z] Daemon has completed initialization
INFO[2019-07-23T07:30:10.513031700Z] API listen on [::]:2376
INFO[2019-07-23T07:30:10.513069100Z] API listen on /var/run/docker.sock
```

But, after updated the `DOCKER_HOST` to `tcp://localhost:2376`, another error bob up.

```
/ # docker -v
Docker version 19.03.0, build aeac9490dc
/ # docker -D info
Client:
 Debug Mode: true

Server:
ERROR: Error response from daemon: Client sent an HTTP request to an HTTPS server.
errors pretty printing info
```

**Comment by jubel-han** [comment]
Just found the workaround, exposing the environment variable `DOCKER_TLS_CERTDIR=''` would solve the problem. ref: https://github.com/docker-library/docker/pull/166

**Comment by frbl** [comment]
confirming, the workaround suggested by jubel-han fixes it (tested on Gitlab CI)

**Comment by peter-c-larsson** [comment]
Since jubel-hans comments are no longer here and I will repost the part that did the trick for me.

Adding the following variable:
```
  DOCKER_TLS_CERTDIR: ''
```
Also changed the docker image tag from `stable` to `stable-dind` and not sure if it was needed.

**Comment by joch** [comment]
Same thing here. We reverted to the `18-dind` tag in Gitab in the meantime.

**Comment by mymusise** [comment]
We meet this error with using the stable tags of `stable` and `stable-dind` images. But `18-dind ` work.

**Comment by jelgersma** [comment]
Specifying `18-dind` as tag fixed it for us.

**Comment by daenny** [comment]
See related issue: https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

**Comment by JanMikes** [comment]
This will literally break half of the Gitlab CI builds that are building Docker images in it and does not have specified version but using tag `docker:dind` 😄

**Comment by janw** [comment]
@JanMikes as the person responsible for the CI runners at our company: it’s already in full effect. People are assuming the runners are broken. 😣

Best example of why going with “blanket tags” like `latest` is a no-no.

**Comment by REBELinBLUE** [comment]
@janw Yep, exactly the same here, everyone was all over me this morning. My fault, shouldn't have set the Jenkins slaves to use `stable-dind`, setting to `18-dind` as suggested has fixed the issue. 🤦‍♂️

**Comment by jozuenoon** [comment]
This affected also builds on Jenkins! Reverted to `18-dind`.

**Comment by buianhthang** [comment]
it's a few hours since we found this problem, why the stable-dind version still 19.xx. are we able to revert to 18.xx?

**Comment by DavidBadura** [comment]
maintainer also have to sleep sometime and are not available around the clock ;-)

**Comment by bachka** [comment]
same thing here.

**Comment by Karreg** [comment]
Confirmed on my side too. Targetting 18-dind is a workaround until the fix, so maintainers don't have to stay awake for the next 24 hours ;)

**Comment by tianon** [comment]
There will not be an update in this repository to "fix" this as 19.03.0 is now released and GA and the TLS behavioral change was intentional (and applied to 19.03+ only by default to give folks two separate escape hatches to opt out -- environment variable or downgrade).

See https://gitlab.com/gitlab-org/gitlab-runner/issues/4501#note_194648542 for a comment from a GitLab team member that sums up my thoughts even better than I could.

**Comment by bachka** [comment]
omg, so we should hardcode in every project, that would be a fun, :dancing_men:

**Comment by kinghuang** [comment]
@tianon While I appreciate that using the `stable` or `latest` tags on the docker image runs the risk of breaking changes, Docker 19.03 has been in RC for 4 months and this change to the image was made just [6 days ago](https://github.com/docker-library/docker/pull/166). I've been testing the docker:19.03.0-rc* images in my GitLab CI pipelines for months in preparation for the release, and didn't run into this breaking change because it wasn't in any of the RCs.

I think it's very poor form to introduce such a breaking change in the last few days of a major release without any notifications.

**Comment by llech** [comment]
@kinghuang IMHO it's always a poor practice to introduce breaking change where it could be easily avoided. 
In that case we have a new feature that breaks old functionality if a variable is set to true. The problem is, that default value is true. I don't quite understand what people doing such things have in mind.  Unfortunately, it's not the first time I see something like that in stable and broadly used open source project.

**Comment by AkihiroSuda** [comment]
TCP connection without tlsverify has been unrecommended for years.

**Comment by JordanP** [comment]
> TCP connection without tlsverify has been unrecommended for years.

If you are running everything locally, it's okay though.

Me and my company got caught by this issue, that's fine but that commit seems a bit rushed, like a big breaking change just before the release... (plz don't revert though)

**Comment by tianon** [comment]
For some values of "okay" -- any container you run (either inside *or* outside the DinD instance) can guess/scan for the IP, connect, and do whatever it wants to your host machine as root. :sweat_smile:

**Comment by REBELinBLUE** [comment]
I thought I'd try setting my jenkins slaves to work correctly, using this manifest generated by the K8S plugin https://gist.github.com/REBELinBLUE/97a5c13c2589bb1f3df5a5b330718eb0

But it doesn't seem to generate all the certificates before the job starts, I added `ls /certs/**` to the start of the job and I end up with

```/certs/ca:
cert.pem
cert.srl
key.pem

/certs/client:
key.pem

/certs/server:
ca.pem
cert.pem
csr.pem
key.pem
openssl.cnf```

if I add the liveness probe it seems to generate the certificates before it fully starts but then when I try to run docker commands I end up with `Error response from daemon: Client sent an HTTP request to an HTTPS server.` (yes I set the ports to 2376)

In the end I have given up and just set `DOCKER_TLS_CERTDIR` to an empty value and set the ports back to 2375 but I'd like to get it working properly

**Comment by tianon** [comment]
Besides setting `DOCKER_HOST` to use port 2376, you need to set `DOCKER_TLS_VERIFY=1` and `DOCKER_CERT_PATH=/certs/client` to tell Docker to use TLS (and where to get certificates to handshake with).

Also, you should only share `/certs/client` with your client containers.

See also:

https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/docker-entrypoint.sh#L22-L33

**Comment by REBELinBLUE** [comment]
Thanks! That works.

Still need to figure out how to only mount the client certificates on the client, annoyingly the jenkins K8S plugin doesn't appear to allow you to configure different mounts per container.

**Comment by tarampampam** [comment]
I fix my self-hosted runners (debian, runners installed using `apt-get`):

```bash
$ nano /etc/gitlab-runner/config.toml
```

```toml
[[runners]]
-  environment = ["DOCKER_DRIVER=overlay2"]
+  environment = ["DOCKER_DRIVER=overlay2","DOCKER_TLS_VERIFY=1","DOCKER_CERT_PATH=/certs/client"]
  [runners.docker]
-    tls_verify = false
    image = "docker:dind"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
-    volumes = ["/cache"]
+    volumes = ["/cache","/certs"]
```

And then:

```bash
$ service gitlab-runner restart
```

**Comment by mqu** [comment]
thanks tarampampam ; this fixed definitely this issue.

**Comment by wileyj** [comment]
using `docker:dind`:
```
INFO[2019-07-30T01:16:04.239203878Z] Starting up                                  
WARN[2019-07-30T01:16:04.241829113Z] could not change group /var/run/docker.sock to docker: group docker not found 
```

reverting to `18-dind` resolved this. 
I plan on creating a new image based on official to manually add the user/group and see if that makes a difference.

**Comment by AkihiroSuda** [comment]
@wileyj The warning you are seeing is unrelated

**Comment by Newspaperman57** [comment]
I have this issue as well, but i cannot revert to 18-dind or similar since they do not have the ppc64le architectures, which means i am currently unable to use dind on any of our servers which uses IBM Power CPU's. I have not yet tried to mess with the certificates, as i can manually build what i need and we only use dind for our build pipeline, but i would definitely appreciate an official fix soon.
![image](https://user-images.githubusercontent.com/1321620/62131938-73641980-b2dc-11e9-8fac-7a68870d9e35.png)

**Comment by tianon** [comment]
Even `docker:dind` doesn't have `ppc64le` support, and hasn't since at least https://github.com/docker-library/docker/commit/6001c15038b05149a83dcc17e1bbeedc92979f6d.

(Docker stopped publishing releases for it quite a while ago; see https://download.docker.com/linux/static/stable/ppc64le/)

**Comment by wileyj** [comment]
> @wileyj The warning you are seeing is unrelated

Indeed, you are correct. 
The following seemed to resolve the issue for me for now based on [this](https://gitlab.com/gitlab-org/gitlab-runner/issues/4501), but I'll have to find a better way to enable the TLS in the future.

the key was this env var in that link: `DOCKER_TLS_CERTDIR=""`

```
11:38:59 ~$ sudo docker run -d \
>   --rm \
>   --privileged  \
>   -p 12375:2375  \
>   -p 12376:2376 \
>   -e DOCKER_TLS_CERTDIR="" \
>   --name dind \
> docker:dind
35e89597e5fde593449f6f01027c5ae240388d0c2a030bc4bd13a42f5e1b2e2d
11:39:04 ~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                 PORTS                                                      NAMES
35e89597e5fd        docker:dind         "dockerd-entrypoint.…"   3 seconds ago       Up 2 seconds           0.0.0.0:12375->2375/tcp, 0.0.0.0:12376->2376/tcp           dind
11:39:06 ~$ docker exec -it dind sh
/ # docker run -d alpine tail -f /dev/null
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
050382585609: Pull complete 
Digest: sha256:6a92cd1fcdc8d8cdec60f33dda4db2cb1fcdcacf3410a8e05b3741f44a9b5998
Status: Downloaded newer image for alpine:latest
82ee20601c943827168c62edb01d9e571749293435d2594059dd1710188ff428
/ # docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
82ee20601c94        alpine              "tail -f /dev/null"   3 seconds ago       Up 1 second                             sad_boyd
/ # 11:39:25docker -H tcp://:12375 ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
82ee20601c94        alpine              "tail -f /dev/null"   17 seconds ago      Up 15 seconds                           sad_boyd
```

**Comment by AkihiroSuda** [comment]
Any reason to keep this issue still open?

**Comment by tianon** [comment]
Currently just using it to catch affected users (hopefully avoiding duplicates).

**Comment by AkihiroSuda** [comment]
Could you edit the top comment to clarify this is not an unresolved bug?

**Comment by tianon** [comment]
GitLab now has a really nice blog post up describing the situation and how to fix it if your environment is affected: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/ :+1:
