### ISSUE TITLE
docker:dind tries to listen to two overlapping ports

### ISSUE THREAD

**Issue by nickygerritsen** [docker-library/docker#175]
It seems that since 7db7eccb7b7507b1a6ba3ef81c6f37b16149cc55 the `docker:dind` container listens on `$DOCKER_HOST` instead of `unix:///var/run/docker.sock` besides listening on `0.0.0.0` port `2375` or `2376`.
However, for GitLab CI to work (in Kubernetes) we have to set the environment variable `DOCKER_HOST` to `tcp://localhost:2375`. This results in `docker:dind` trying to bind to 2375 twice (if `DOCKER_TLS_CERTDIR=""` which is needed for now to get stuff working until Gitlab offers an option to share the certdir), which gives a `bind: address already in use` error.

For now I have fixed this by setting `DOCKER_HOST` to `tcp://localhost:2378`, letting Docker use a port that is not in use yet, but it seems to me that this is not an ideal solution.

Note that it not only broke for `docker:dind` but also for other versions like `docker:18-dind`.

**Comment by alexandrujieanu** [comment]
My setup is using Gitlab CI with docker-dind (https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-workflow-with-docker-executor), with 
```variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
```

I tried switching the port to `2378`, it didn't work.

It worked by removing the `DOCKER_HOST` variable.

**Comment by nickygerritsen** [comment]
Might be that the fix for port `2378` is specific to the Kubernetes runner :) .

**Comment by paolomainardi** [comment]
We are facing the same issue, as a result all our CI pipelines todays are broken, our quick fix for now is downgrade to `docker:17-dind`

**Comment by dc2tom** [comment]
I've confirmed that 18.09.7-dind fixes the issue for now.  18.08.8 is the problem tag.  I wish I hadn't advised all of our teams to roll back to 18-dind and not the explicit version the other day :(

**Comment by jakubfijalkowski** [comment]
If someone is using `v19` line, I can confirm that `19.03.0` also works.

**Comment by maresja1** [comment]
@dc2tom Fixing to specific version does not help - I advised our team to rollback from latest to 18.09.8-dind and it worked fine for a week. And guess what - this version was **overwritten** 4hrs ago. Unbelievable.

**Comment by prawana-perera** [comment]
> If someone is using `v19` line, I can confirm that `19.03.0` also works.

I tried `19.03-dind`, this did not work, same issue

**Comment by peter-c-larsson** [comment]
The version to use is `19.03.0-dind` since the `19.03.1-dind` is the one failing and that is the same version as `19.03-dind`

Getting used to look at the tag times here: https://hub.docker.com/_/docker?tab=tags

**Comment by paolomainardi** [comment]
19.03.0-dind is failing as well for the TLS thing on #176

**Comment by Eji4h** [comment]
> > If someone is using `v19` line, I can confirm that `19.03.0` also works.
> 
> I tried `19.03-dind`, this did not work, same issue

It work for me.

**Comment by azzaka** [comment]
Soooo.... essentially if we add:

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

to the gitlab-ci file it will disable the TLS flag, and if we add:

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

It will enable the flag. Not tested it yet, hoping it will fix it.

**Comment by tmaczukin** [comment]
@azzaka From what I see, any of:

1. Remove `DOCKER_HOST: tcp://docker/237x`
1. Use strict version: `docker:19.03.0-dind`/`docker:18.09.7-dind`

should help.

The TLS problem was discussed last week, also in this issue tracker (https://github.com/docker-library/docker/issues/170). And at the end you can find a link to our blog post, that describes what happened and how TLS problem can be resolved: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/.

**Comment by tmaczukin** [comment]
I've proposed #177 as a solution for this issue.
