### ISSUE TITLE
cannot run dind without tls

### ISSUE THREAD

**Issue by andreas-sch-b** [docker-library/docker#176]
This seems to be somehow related to #175, but is not exactly the same.

With the latest version 19.03.1 of docker:dind it's not possible to start dind without tls anymore. 
In the past it worked by just setting the env variable `DOCKER_TLS_CERTDIR=""`. Since 19.03.0 it seems not possible any more. It always starts with 2376. From the code I don't see another chance to enter the branch for non-tls.

https://github.com/docker-library/docker/blob/c01ffa41486f70c34f020c769bc5bddf106367ea/19.03/dind/dockerd-entrypoint.sh#L123

The reason might be line 56: https://github.com/docker-library/docker/blob/c01ffa41486f70c34f020c769bc5bddf106367ea/19.03/Dockerfile#L56

**Comment by tmaczukin** [comment]
@andreas-sch-b As described in #175, remove the `DOCKER_HOST=...` definition when starting the images, since this is probably what prevents your DinD image from being started.

**Comment by andreas-sch-b** [comment]
@tmaczukin indeed, that solves the problem. Thanks! Closing the issue.
