### ISSUE TITLE
docker:dind healthcheck failing if setting DOCKER_TLS_CERTDIR to ""

### ISSUE THREAD

**Issue by mkg20001** [docker-library/docker#182]
When setting the environment variable `DOCKER_TLS_CERTDIR` to an empty string, the docker host will start without using tls and therefore will listen on 2375.

The problem is that the healthcheck expects it to listen on 2376, and as such fails.

The healthcheck should check if `[ -n "${DOCKER_TLS_CERTDIR:-}" ]` (if the variable is not an empty string) and try to connect to 2375 with HTTP instead

**Comment by tianon** [comment]
This image doesn't define a healthcheck though :confused:

**Comment by mkg20001** [comment]
Weird.
Came across a healthcheck problem while debugging https://gitlab.com/gitlab-org/gitlab-ce/issues/65619, but seems it's gitlab's fault
