### ISSUE TITLE
Can't make docker login to work from within container

### ISSUE THREAD

**Issue by whoan** [docker-library/docker#188]
I don't know if this is the expected behavior, but if I run `docker login` from a container from docker image, it tries the following and fails:
    $ docker run -ti --rm docker:dind ash

    # docker login
    Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
    Username: me
    Password: 
    error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on 8.8.8.8:53: no such host

As you can see, it tries (unsuccessfully) to connect to host *docker* and fails. Why? Is it expected?

**Comment by tao12345666333** [comment]
If you want to using `docker:dind`, you should using 

```
(MoeLove) ➜  ~ docker run --rm -d --privileged docker:dind 
b2e24dbb2f5188f34d6cd751bb26ced922cb6277084773207924449f2ebfbba0
(MoeLove) ➜  ~ docker exec -it $(docker ps -ql) sh 
/ # docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: taobeier
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

```

**Comment by tao12345666333** [comment]
> As you can see, it tries (unsuccessfully) to connect to host _docker_ and fails. Why?

We will set the `DOCKER_HOST` env.  So docker CLI will connect to `tcp://docker:2375`

```
(MoeLove) ➜  ~ docker run --rm -it docker:dind sh
/ # env |grep DOCKER_HOST
DOCKER_HOST=tcp://docker:2375
```

**Comment by whoan** [comment]
Thanks!
