### ISSUE TITLE
devmapper: Udev sync is not supported.

### ISSUE THREAD

**Issue by raarts** [docker-library/docker#19]
Full error message: `devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver.`

Default the vfs driver is used, which is _very_ slow. The devicemapper driver is the recommended one I think?

**Comment by thomas15v** [comment]
Any news about this issue yet? Atm I figured out you can only use the devicemapper if you add `--storage-opt dm.override_udev_sync_check=true`, to the docker:dind run configuration.

**Comment by tianon** [comment]
I would definitely not recommend devicemapper unless you're prepared to set up a dedicated LVM block to point your Docker daemon at (and let Docker manage).  Additionally, this image uses static binaries, which do not support devicemapper (hence the error you're getting trying to use it).

I'd personally recommend `overlay2`, but `overlay`, `aufs`, and `btrfs` are also good alternatives (depending on your environment and your needs).
