### ISSUE TITLE
Credential Helper not configured

### ISSUE THREAD

**Issue by cmorty** [docker-library/docker#190]
When running logging into a local registry I always get:
```
echo $CI_JOB_TOKEN | docker  login -u gitlab-ci-token --password-stdin $CI_REGISTRY
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```
Shouldn't this somehow be configured globally?

**Comment by tianon** [comment]
In a perfect world, yes, but unfortunately the situation on Linux is a lot more complicated than that.  On MacOS, we've got the keyring as the One True Source for credentials.  On Windows, we've got the Credential Manager which serves a similar function globally.

On Linux, we have GNOME Keyring, KWallet, `pass`, etc. -- there's no One True Source, and each choice has different strengths and drawbacks, so there really isn't a sane default we could provide out-of-the-box.

**Comment by cmorty** [comment]
Ok, however we are within a docker container. Can't just any one of them be installed and configured. As I'm running from a CI and the container is thrown away afterwards anyway, I'm even happy saving it in plain text, but as far as I can see there is no way to suppress the warning besides `grep` and co. - Manipulating `config.json` directly feels kind of bad, too.

**Comment by tianon** [comment]
Not really -- GNOME Keyring and KWallet expect to interact with a desktop session, and the usage of `pass` is pretty unpleasant (requiring an extra password), so this is really something each user has to configure for themselves if it's something that's a problem for them.

I typically use the `DOCKER_CONFIG` environment variable to set my `~/.docker` location to something local to the CI job I'm running, which helps mitigate at least some of this.

**Comment by cmorty** [comment]
> I typically use the `DOCKER_CONFIG` environment variable to set my `~/.docker` location to something local to the CI job I'm running, which helps mitigate at least some of this.

This would still require me do dump the credentials into the docker config manually (I get a new Token for each job). :/ IMO the best would be a `--yes-store-my-pass-in-plain-text` option that suppresses the warning. ;)
