### ISSUE TITLE
Getting error response: HTTP status: 503 Service Unavailable

### ISSUE THREAD

**Issue by DiegoTc** [docker-library/docker#192]
Hi
I'm trying to download the latest image from docker 
```
 docker pull docker:stable
```

But I'm getting this error
```
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

Wondering if it's a global issue?

**Comment by wglambert** [comment]
Yeah it looks like they're having some issues https://github.com/docker/hub-feedback/issues/1897

Going to close since the hub-feedback repo is the appropriate place for this
