### ISSUE TITLE
Docker's Makefile uses "docker" namespace

### ISSUE THREAD

**Issue by tianon** [docker-library/docker#2]
Docker's development `Makefile` currently uses the `docker` namespace for building development images: https://github.com/docker/docker/blob/3ea59f8991a4d70254582759044316e522a09ee9/Makefile#L29

We need to decide if this is a problem, and whether we should fix it by naming this image something else, or by sending a PR to Docker.

Especially wondering @jfrazelle's opinion on this one.

I've just barely reorganized this repo so that we can have `docker:latest` be just the Docker CLI, and `docker:dind` include all the hacky bits to do Docker-in-Docker, since they're pretty intrusive and require `--privileged`, and just being able to use the CLI from inside an image would definitely be useful.

**Comment by jfrazelle** [comment]
oh man hmmmm maybe dockerdev, docker-engine, naming things is so hard, what if we just did engine

**Comment by tianon** [comment]
For this image's name, or as a PR against `Makefile` to change the name people build Docker with?

**Comment by jfrazelle** [comment]
oh def our image should be called docker

but idk what to name the dev docker we build and test in ;)

**Comment by tianon** [comment]
Right, OK. :+1:

"docker-dev" is an official image that has builds of Docker's own
Dockerfile, so maybe we should just use that same name? (especially since
it only has builds of the releases)

**Comment by jfrazelle** [comment]
ah oerfect :)

On Fri, May 1, 2015 at 5:20 PM, Tianon Gravi <notifications@github.com>
wrote:

> Right, OK. :+1:
>
> "docker-dev" is an official image that has builds of Docker's own
> Dockerfile, so maybe we should just use that same name? (especially since
> it only has builds of the releases)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/docker/issues/2#issuecomment-98266277>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
perfect*

On Fri, May 1, 2015 at 5:21 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> ah oerfect :)
>
> On Fri, May 1, 2015 at 5:20 PM, Tianon Gravi <notifications@github.com>
> wrote:
>
>> Right, OK. :+1:
>>
>> "docker-dev" is an official image that has builds of Docker's own
>> Dockerfile, so maybe we should just use that same name? (especially since
>> it only has builds of the releases)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/docker-library/docker/issues/2#issuecomment-98266277>
>> .
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by tianon** [comment]
Fixed by docker/docker#12936 :+1:
