### ISSUE TITLE
dind-rootless: failed to start up dind rootless in k8s due to max_user_namespaces

### ISSUE THREAD

**Issue by hxin19** [docker-library/docker#201]
I tried to start ding-rootless image in k8s and got "error: attempting to run rootless dockerd but need 'user.max_user_namespaces' (/proc/sys/user/max_user_namespaces) set to a sufficiently large value".
Any workaround? Thanks!

**Comment by AkihiroSuda** [comment]
Add user.max_user_namespaces=28633 to /etc/sysctl.conf (or /etc/sysctl.d) and run sudo sysctl -p

https://github.com/moby/moby/blob/master/docs/rootless.md#rhelcentos-7

**Comment by hxin19** [comment]
Thanks for the reply but it didn't solve the problem. As I mentioned, it is rootless, there's no way to edit /etc/sysctl.conf inside dind-rootless instance and no sudo either.

**Comment by tianon** [comment]
You need to perform these changes on the Kubernetes host systems, not in the containers.
