### ISSUE TITLE
Lookup error in Docker image

### ISSUE THREAD

**Issue by zzj0402** [docker-library/docker#202]
# Output
```
docker: error during connect: Post http://docker:2375/v1.40/containers/create: dial tcp: lookup docker on 192.168.1.1:53: no such host.
```
# Reproduction
```
# docker run --privileged -it docker:dind sh
```
Inside the image, run: 
```
# docker run hello-world
```

**Comment by tao12345666333** [comment]
Please see: https://github.com/docker-library/docker/issues/200#issuecomment-550089770

**Comment by zzj0402** [comment]
> Please see: [#200 (comment)](https://github.com/docker-library/docker/issues/200#issuecomment-550089770)

Update the tutorial:
https://hub.docker.com/_/docker?tab=description

**Comment by yosifkit** [comment]
The tutorial on the Hub does not say to run the dind container interactively (with `sh`), but says to run it in the background and connect from another container.

Duplicate #200.
