### ISSUE TITLE
Doesn't work on Windows Server 2019

### ISSUE THREAD

**Issue by goldsam** [docker-library/docker#204]
This image doesn't work on Windows Server 2019:

Invoking any of the commands: 
* ` docker run  docker:18.05-dind`
* ` docker run  docker:latest`
* ` docker run  docker:stable`

produces the following error message:

```
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries.
```

Current docker version output by `docker version`:
```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by goldsam** [comment]
Looks like I simply needed to enabled experimental features by adding 
```json
  "experimental": true
```
to my `daemon.json`.

**Comment by abjinugu** [comment]
how did this work for you? I'm getting below message.

"failed to start service utility VM (createreadwrite): kernel 'C:\Program Files\Linux Containers\kernel' not found"
