### ISSUE TITLE
Include SSH client for SSH protocol in DOCKER_HOST

### ISSUE THREAD

**Issue by a-abella** [docker-library/docker#206]
Docker 18.09 added SSH as a supported protocol for the Docker client `DOCKER_HOST` configuration. This configuration requires an SSH client to be installed. I noticed that the `docker-git` images include SSH, but the base images do not. As `DOCKER_HOST` over SSH is now built-in Docker functionality, it may be correct to include SSH with the base image in order to preserve that functionality.

**Comment by tianon** [comment]
Good catch; I tested and it adds ~6MB, which is totally reasonable, thus https://github.com/docker-library/docker/pull/207 :+1:
