### ISSUE TITLE
Experimental

### ISSUE THREAD

**Issue by cirocosta** [docker-library/docker#21]
Hey,

just wondering, wouldn't it make sense to have an `docker:experimental` which builds using https://experimental.docker.com/? What do you think?

My main intention is to test `docker deploy`, which as far as i understand is under `experimental` right now.

Thx!

**Comment by tianon** [comment]
Ah, interesting point.  Previously, `experimental` was essentially daily builds from `master`, but now it's officially built for each release too, so I agree that incorporating it in some way here would make sense.

I've been re-building [`tianon/docker-master`](https://hub.docker.com/r/tianon/docker-master/) for a while now which has tags both for the nightly master builds (https://master.dockerproject.org/) and for experimental, which might be of interest or use in the interim while we figure out the best way to incorporate experimental officially here.
