### ISSUE TITLE
Run dind without socket (or make socket path configurable)

### ISSUE THREAD

**Issue by chulkilee** [docker-library/docker#215]
Currently, it always mount to the default socket path. The problem is, if I have already other docker daemon socket mounted at the path, dind container failed to start as it cannot create the docket.

```
failed to load listeners: can't create unix socket /var/run/docker.sock: device or resource busy
```

For now, I'm overwriting entrypoint and pass all options, but it would be nice if I can choose not to use socket, or specify custom socket path.

```
 docker run --rm --privileged --entrypoint "" docker:19.03.5-dind dockerd --host=tcp://127.0.0.1:2375
```

**Comment by tianon** [comment]
I'm not sure what your intended use case for this is, but if you want to change the default location of the `--host` flag our entrypoint adds, just set `DOCKER_HOST` to `unix:///...` and it should be honored: https://github.com/docker-library/docker/blob/356175627e220b4bd8f4e9201e075ee3431ce081/dockerd-entrypoint.sh#L104-L108

That being said, if your intention is to disable TLS and our default unix socket, then bypassing our entrypoint to run `dockerd` directly is the best solution.

**Comment by chulkilee** [comment]
Oh, right. I thought `DOCKER_HOST` with `tcp://`... will be honored, but it's not actually - so setting `DOCKER_HOST` to custom path will avoid mounting the socket at the default path.

Closing it as there is a way to do it. Thanks @tianon !

**Comment by PavelPolyakov** [comment]
hi @chulkilee, @tianon,

I met an issue alike, and hope you can help me to understand why it doesn't work when you run it right away.

So when I do:
```sh
docker run -it --privileged docker:stable-dind sh
```
and then run
```sh
docker run hello-world
```

it throws me an error:
```
docker: error during connect: Post http://docker:2375/v1.40/containers/create: dial tcp: lookup docker on 192.168.65.1:53: no such host.
```

But when I run container aside, then connect to it:
```sh
docker run --rm --privileged --name dind-docker -d docker:stable-dind
docker exec -it dind-docker /bin/sh
```

then `docker run hello-world` works.

Why the first case doesn't?

Regards,

**Comment by tianon** [comment]
Because the first case starts `sh` *instead of* `dockerd`, where the second case you start `dockerd` then run `sh` as a second process.

**Comment by PavelPolyakov** [comment]
@tianon tnx! Didn't realise that
