### ISSUE TITLE
Is it possible to install a plugin at build time?

### ISSUE THREAD

**Issue by FedericoPonzi** [docker-library/docker#219]
Hello,

I'm wondering if there is a way to add a plugin (say the Amazon CloudWatch Logs logging driver) at build time. Otherwise, when the image is started, I would need to run the docker command to download the plugin. 

Is there a way to avoid this and get it included at build time?

Thanks!

**Comment by wglambert** [comment]
Closing as this seems resolved to the extent that we can do as maintainers.
