### ISSUE TITLE
MacOS dind cant connect to tcp://docker:2375

### ISSUE THREAD

**Issue by ZhangJianAo** [docker-library/docker#225]
MacOS Mojave 10.14.6

Docker 19.03.8

Start docker in docker from command: `docker run -it --privileged --name some-docker -d docker:stable-dind`

Then get version using command: `docker run -it --rm --link some-docker:docker docker version`

The command returned: `Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?`

The following is logs output:
`
INFO[2020-04-14T08:50:16.061943345Z] Starting up
WARN[2020-04-14T08:50:16.063145678Z] could not change group /var/run/docker.sock to docker: group docker not found
INFO[2020-04-14T08:50:16.063973262Z] libcontainerd: started new containerd process  pid=54
INFO[2020-04-14T08:50:16.064024727Z] parsed scheme: "unix"                         module=grpc
INFO[2020-04-14T08:50:16.064053734Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-04-14T08:50:16.064071104Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-04-14T08:50:16.064090178Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-04-14T08:50:16.080334406Z] starting containerd                           revision=7ad184331fa3e55e52b890ea95e65ba581ae3429 version=v1.2.13
INFO[2020-04-14T08:50:16.080866185Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2020-04-14T08:50:16.081036997Z] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[2020-04-14T08:50:16.081487107Z] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[2020-04-14T08:50:16.081624916Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
WARN[2020-04-14T08:50:16.086810868Z] failed to load plugin io.containerd.snapshotter.v1.aufs  error="modprobe aufs failed: "ip: can't find device 'aufs'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1"
INFO[2020-04-14T08:50:16.086926261Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2020-04-14T08:50:16.087014149Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2020-04-14T08:50:16.087214577Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2020-04-14T08:50:16.087473222Z] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2020-04-14T08:50:16.087530931Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2020-04-14T08:50:16.087592299Z] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[2020-04-14T08:50:16.087646910Z] could not use snapshotter aufs in metadata plugin  error="modprobe aufs failed: "ip: can't find device 'aufs'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1"
WARN[2020-04-14T08:50:16.087671595Z] could not use snapshotter zfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
INFO[2020-04-14T08:50:16.090737499Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2020-04-14T08:50:16.090806350Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2020-04-14T08:50:16.090877121Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.090938054Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.090976403Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.091013975Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.091072976Z] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.091140285Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.091175962Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.091232246Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2020-04-14T08:50:16.091387001Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2020-04-14T08:50:16.091524769Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2020-04-14T08:50:16.091815513Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2020-04-14T08:50:16.091885144Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2020-04-14T08:50:16.091955374Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092013402Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092039208Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092121788Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092170716Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092226815Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092290846Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092346193Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092404043Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2020-04-14T08:50:16.092586627Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092646148Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092695852Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092716404Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2020-04-14T08:50:16.092930206Z] serving...                                    address="/var/run/docker/containerd/containerd-debug.sock"
INFO[2020-04-14T08:50:16.093052544Z] serving...                                    address="/var/run/docker/containerd/containerd.sock"
INFO[2020-04-14T08:50:16.093173759Z] containerd successfully booted in 0.013580s
INFO[2020-04-14T08:50:16.100218542Z] parsed scheme: "unix"                         module=grpc
INFO[2020-04-14T08:50:16.100272691Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-04-14T08:50:16.100300895Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-04-14T08:50:16.100381505Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-04-14T08:50:16.102526236Z] parsed scheme: "unix"                         module=grpc
INFO[2020-04-14T08:50:16.102561571Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-04-14T08:50:16.102573953Z] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-04-14T08:50:16.102580037Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-04-14T08:50:16.143555744Z] Loading containers: start.
WARN[2020-04-14T08:50:16.153985651Z] Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'
ip: can't find device 'br_netfilter'
modprobe: can't change directory to '/lib/modules': No such file or directory
, error: exit status 1
INFO[2020-04-14T08:50:16.201696915Z] Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2020-04-14T08:50:16.234428772Z] Loading containers: done.
INFO[2020-04-14T08:50:16.255795723Z] Docker daemon                                 commit=afacb8b7f0 graphdriver(s)=overlay2 version=19.03.8
INFO[2020-04-14T08:50:16.256147287Z] Daemon has completed initialization
INFO[2020-04-14T08:50:16.282886171Z] API listen on [::]:2376
INFO[2020-04-14T08:50:16.282895950Z] API listen on /var/run/docker.sock
`

**Comment by tao12345666333** [comment]
Please use this command to start dind. 

```
docker run  -d --privileged docker:stable-dind
```

**Comment by tianon** [comment]
See the section titled "TLS" on https://hub.docker.com/_/docker -- you'll need to either adjust `DOCKER_TLS_CERTDIR` to disable TLS, or copy the client certificate into your second container (through a shared volume, etc).

**Comment by lxdraw** [comment]
I am having a similar problem. I am trying to disable TLS per the link above.

I start the daemon:
`docker run --privileged --name dind --network dind-test --network-alias docker -e DOCKER_TLS_CERTDIR= -d docker:dind dockerd`

Then connect to it from a second container:
`docker run --rm --network dind-test -e DOCKER_TLS_CERTDIR= docker:latest version`

Results in:

> Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?

I cannot figure out from the link above what I am missing?

**Comment by tianon** [comment]
When you specify `dockerd` as the command, you've requested to not get our entrypoint's behavior, which is where the listening socket at 2375 comes from -- if you use `docker run --privileged --name dind --network dind-test --network-alias docker -e DOCKER_TLS_CERTDIR= -d docker:dind` instead, your example should work.
