### ISSUE TITLE
Docker:stable, Alpine Linux => python (missing)

### ISSUE THREAD

**Issue by AlexGoranov** [docker-library/docker#240]
I have a pipeline which deploys my container from GitLab. Last deployment was 5 days ago and went without any problems. Today I deploy it and get the following error:

    $ apk add --no-cache curl python py-pip
     fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
     fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
     ERROR: unsatisfiable constraints:
       python (missing):
         required by: world[python]

My job definition is:

    my-deploy:
      type: my-deploy
      image: docker:stable
      script:
        - apk update
        - apk add --no-cache curl python py-pip <-- Here the erorr happens
        ...

**Comment by solvindovatten** [comment]
Hello! I have the exact same problem!

Even with just a clean docker container I get this problem.

`docker run -it docker:latest /bin/ash
# apk add python
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
`

Explicitly installing python3/python2 seems to work, though!

19.03.11 has the problem, but 19.03.10 does not, and installs python2 when you just write "python".

**Comment by mgrahamx** [comment]
Also experiencing the exact same issue.

**Comment by Lebed71** [comment]
Fast fix for using now - image: docker:19.03.10

**Comment by wglambert** [comment]
Looks like this is the commit https://git.alpinelinux.org/aports/commit/?h=3.12-stable&id=5ad0ec7da1064361cc74d56edf7524960f49ef9b
>main/python2: remove python symlink and stop providing python

And specifying `python2` works
```console
$ docker run -it --rm docker
Unable to find image 'docker:latest' locally
latest: Pulling from library/docker
df20fa9351a1: Pull complete 
25ad7478873d: Pull complete 
4684f6177b5d: Pull complete 
1d105a01b85c: Pull complete 
d87316014961: Pull complete 
ae7f709568fa: Pull complete 
63f9e63bc2f8: Pull complete 
Digest: sha256:42e9d5ccd8794b13466a0d8b2686d035504fad6b996e883152ae3c56125bc6dc
Status: Downloaded newer image for docker:latest

/ # apk add python
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]

/ # apk add python2
(1/7) Installing libbz2 (1.0.8-r1)
(2/7) Installing expat (2.2.9-r1)
(3/7) Installing libffi (3.3-r2)
(4/7) Installing gdbm (1.13-r1)
(5/7) Installing readline (8.0.4-r0)
(6/7) Installing sqlite-libs (3.32.1-r0)
(7/7) Installing python2 (2.7.18-r0)
Executing busybox-1.31.1-r16.trigger
OK: 51 MiB in 27 packages
```

**Comment by Nevermore-dh** [comment]
> I have a pipeline which deploys my container from GitLab. Last deployment was 5 days ago and went without any problems. Today I deploy it and get the following error:
> 
> ```
> $ apk add --no-cache curl python py-pip
>  fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
>  fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
>  ERROR: unsatisfiable constraints:
>    python (missing):
>      required by: world[python]
> ```
> 
> My job definition is:
> 
> ```
> my-deploy:
>   type: my-deploy
>   image: docker:stable
>   script:
>     - apk update
>     - apk add --no-cache curl python py-pip <-- Here the erorr happens
>     ...
> ```

https://stackoverflow.com/a/62169663/8043118

**Comment by subhamg** [comment]
Add this command to your Dockerfile. Don't forget to mention the python version.

`RUN apk --no-cache add --virtual builds-deps build-base python3
`
