### ISSUE TITLE
Docker in Docker : TLS unable to set right certificates

### ISSUE THREAD

**Issue by Nithinbs18** [docker-library/docker#248]
Hello team,

I have my applications running behind a corporate proxy, and I use docker:19.03-dind  the local registry works fine as an insecure registry but when I try to pull any images from the docker hub it throws a certificate error "Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority" I have all proxy variables i.e HTTP_PROXY, HTTPS_PROXY set. 
Is there a workaround to disable the TLS check?
Thanks in advance.

**Comment by tianon** [comment]
Did you set those proxy variables on the Docker-in-Docker daemon container specifically, or just on your host or client environment?

**Comment by Nithinbs18** [comment]
hey,

Yes the env variables were set.
I figured it out I had to manually copy the proxy certificates and run update-ca-certificates  i.e.

....
COPY ./ca-certificates/ /usr/local/share/ca-certificates
RUN update-ca-certificates command
