### ISSUE TITLE
No such image

### ISSUE THREAD

**Issue by Gaston2018** [docker-library/docker#253]
Hi all, I have this issue when try to execute the pipeline to build

Running with gitlab-runner 11.7.0 (8bb608ff)
  on f1s01317-server-integraciones-runner-weblogic12c ybs2VWpm
Using Docker executor with image docker:stable ...
ERROR: Preparation failed: Error: No such image: docker:stable (executor_docker.go:188:0s)
Will be retried in 3s ...
Using Docker executor with image docker:stable ...
ERROR: Preparation failed: Error: No such image: docker:stable (executor_docker.go:188:0s)
Will be retried in 3s ...
Using Docker executor with image docker:stable ...
ERROR: Preparation failed: Error: No such image: docker:stable (executor_docker.go:188:0s)
Will be retried in 3s ...
ERROR: Job failed (system failure): Error: No such image: docker:stable (executor_docker.go:188:0s)

The same error appears using docker:latest

The pipeline is the following:

stages:
  - build

build_stage:
  image: docker:stable
  stage: build
  script: echo "Building the app"
    - docker build -t osb2/weblogic-producer12c -f Dockerfile.Producer
  only:
    - master

Thanks in advanced.

Best regards.

**Comment by wglambert** [comment]
Looks like an issue specific to Gitlab-runner https://gitlab.com/gitlab-org/gitlab/-/issues/218331

Since the image is available on Dockerhub and has no errors when pulling normally there's nothing actionable we could do to alleviate this
```console
$ docker pull docker:stable
stable: Pulling from library/docker
df20fa9351a1: Pull complete 
25ad7478873d: Pull complete 
4684f6177b5d: Pull complete 
46e300cec669: Pull complete 
63038576ad94: Pull complete 
0fdb76c4706c: Pull complete 
cb7edeffdfd5: Pull complete 
Digest: sha256:f9a24a777e813e2692920a86530355e3840d0271464fd486bd8708aa018d0ac6
Status: Downloaded newer image for docker:stable
docker.io/library/docker:stable
```
