### ISSUE TITLE
Ability to use different storage drivers

### ISSUE THREAD

**Issue by JorritSalverda** [docker-library/docker#26]
In need a docker-in-docker container to build docker containers in our CI system running on Kubernetes (see https://github.com/kubernetes/kubernetes/issues/33745).

The 1.12.1-dind image looks perfect for this, the only drawback being that I can't select the storage driver at run time as it's hardcoded into https://github.com/docker-library/docker/blob/746d9052066ccfbcb98df7d9ae71cf05d8877419/1.12/dind/dockerd-entrypoint.sh.

Could this be done either through an environment variable with default value vfs or if different storage drivers need different dependencies in separate builds?

**Comment by yosifkit** [comment]
If you add your own to the docker run it overrides the entrypoint one:
```console
$ docker run --privileged --name some-overlay-docker -d docker:dind --storage-driver=overlay
```
> https://github.com/docker-library/docs/tree/master/docker#custom-daemon-flags

**Comment by JorritSalverda** [comment]
Thanks, I missed that piece of documentation.

**Comment by treeder** [comment]
@yosifkit any interest in a few lines of extra shell script to auto detect the available file systems and choose the best one automatically? That's what we've done to avoid having to pass in the flag.

**Comment by tianon** [comment]
Docker itself essentially does that when the value is unspecified, but it's
prone to choosing "devicemapper", which is almost always a bad idea when
it's chosen automatically, hence we went for hard-coding the only option
which is definitely supported everywhere (as an explicit design goal,
especially for CI and testing).
