### ISSUE TITLE
docker:20.10.0-dind-rootless images missing

### ISSUE THREAD

**Issue by candrews** [docker-library/docker#277]
There are no images for any architectures for `docker:20.10.0-dind-rootless`, see https://hub.docker.com/_/docker?tab=tags&page=1&ordering=last_updated&name=20.10.0-dind-rootless

![image](https://user-images.githubusercontent.com/194713/101825444-9b33d600-3afb-11eb-98af-931fecb2979f.png)

Is that expected? When will images appear?

Thanks!

**Comment by tianon** [comment]
https://github.com/docker-library/docker#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet -> https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what -> https://github.com/docker-library/official-images/pull/9253

Builds are in queue :smile:
