### ISSUE TITLE
undeclared bashisms

### ISSUE THREAD

**Issue by DanielDent** [docker-library/docker#28]
docker-entrypoint.sh (i.e. in docker/1.12/docker-entrypoint.sh as well as other places) contains non-portable shell code.

On a debian system with dash as the default shell, it does not work. Declaring #!/bin/bash at the top alleviates the issue.

**Comment by tianon** [comment]
Can you give some examples of which bits of code are non-portable?  We're running it with Alpine's `/bin/sh`, which is provided by Busybox (not Bash -- we don't even install Bash IIRC).

**Comment by tianon** [comment]
Is it the `if [ "${1:0:1}" = '-' ]; then` that's failing?  IIRC, both Bash and Busybox support that notation, but I seem to recall that Dash does throw a hissy fit over it.

**Comment by tianon** [comment]
Indeed, made the following changes to needle this out:
```diff
diff --git a/1.12/Dockerfile b/1.12/Dockerfile
index 4764465..ee7b8dd 100644
--- a/1.12/Dockerfile
+++ b/1.12/Dockerfile
@@ -1,9 +1,4 @@
-FROM alpine:3.4
-
-RUN apk add --no-cache \
-               ca-certificates \
-               curl \
-               openssl
+FROM buildpack-deps:jessie-curl
 
 ENV DOCKER_BUCKET get.docker.com
 ENV DOCKER_VERSION 1.12.1
diff --git a/1.12/docker-entrypoint.sh b/1.12/docker-entrypoint.sh
index 664a74e..a7d8cfa 100755
--- a/1.12/docker-entrypoint.sh
+++ b/1.12/docker-entrypoint.sh
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env dash
 set -e
 
 if [ "${1:0:1}" = '-' ]; then
```
got:
```console
/usr/local/bin/docker-entrypoint.sh: 4: /usr/local/bin/docker-entrypoint.sh: Bad substitution
```
