### ISSUE TITLE
19.03-dind-rootless image fails lacking `experimental`

### ISSUE THREAD

**Issue by phlax** [docker-library/docker#281]
When trying to run `19.03-dind-rootless` the container fails and checking the logs i see:

```
subject=CN = docker:dind client
Getting CA Private Key
/certs/client/cert.pem: OK
time="2020-12-13T12:10:25.108592435Z" level=info msg="Starting up"
rootless mode is supported only when running in experimental mode
[rootlesskit:child ] error: command [dockerd --host=unix:///run/user/1000/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem] exited: exit status 1
[rootlesskit:parent] error: child exited: exit status 1
```

running the same command with `20-dind-rootless` works fine

**Comment by tianon** [comment]
Correct, this is the expected behavior -- see https://github.com/docker-library/docker/pull/174 and https://github.com/moby/moby/pull/40759.

**Comment by phlax** [comment]
hi - can i clarify. 

Does the configuration *inside* the container need to be set to experimental ?

My host config *is* experimental, but i would have thought that was not relevant.

if its the containers config, im trying to understand why it doesnt work out of the box (with `--privileged` set)

**Comment by yosifkit** [comment]
> Does the configuration inside the container need to be set to experimental ?

Yes, the container `dockerd` needs the `--experimental` flag (or `experimental` set via a config file).

>My host config is experimental, but i would have thought that was not relevant.

Correct, the host `dockerd` experimental has no bearing.

> if its the containers config, im trying to understand why it doesnt work out of the box (with `--privileged` set)

` --privileged` is just *how* the `dockerd` container is run, not the configuration that `dockerd` is given when running. 

> I was toying with automatically adding `--experimental` as well, but wanted to enforce that being opt-in so that users don't switch without realizing what they're doing (since it does require some changes in usage).
>
> \- https://github.com/docker-library/docker/pull/174#issue-302686130
