### ISSUE TITLE
Multiarch support for tag 20.10.3-dind

### ISSUE THREAD

**Issue by wngr** [docker-library/docker#293]
Hey there,

currently, the [images](https://hub.docker.com/_/docker?tab=tags&page=1&ordering=last_updated&name=dind) tagged with `20.10.3-dind` are only published for amd64 and arm64, but not for armv6 and armv7:

![Screenshot from 2021-02-11 10-17-40](https://user-images.githubusercontent.com/7816612/107618830-7fab8f80-6c52-11eb-904b-87c78edc3891.png)

However, the `dind` tag is published for all four architectures:
![Screenshot from 2021-02-11 10-17-31](https://user-images.githubusercontent.com/7816612/107618832-80442600-6c52-11eb-8379-96f31bddd236.png)

Would be great if the missings archs could also be published to `20.10.3-dind`, so I can fix the version in my `Dockerfile`.

Thanks

**Comment by tianon** [comment]
See #260
