### ISSUE TITLE
docker:dind 20.10 is slow to start when TLS is disabled.

### ISSUE THREAD

**Issue by acornax** [docker-library/docker#294]
docker:dind 20.10 is slow to start when TLS is disabled. From looking at dockerd logs, the cause is clear.

```
time="2021-02-05T23:51:10.090433317Z" level=warning msg="Binding to an IP address without --tlsverify is deprecated. Startup is intentionally being slowed down to show this message" host="tcp://0.0.0.0:23
75"
time="2021-02-05T23:51:10.090713833Z" level=warning msg="Please consider generating tls certificates with client validation to prevent exposing unauthenticated root access to your network" host="tcp://0.0
.0.0:2375"
time="2021-02-05T23:51:10.090768981Z" level=warning msg="You can override this by explicitly specifying '--tls=false' or '--tlsverify=false'" host="tcp://0.0.0.0:2375"
time="2021-02-05T23:51:10.090786304Z" level=warning msg="Support for listening on TCP without authentication or explicit intent to run without authentication will be removed in the next release" host="tcp
://0.0.0.0:2375"
```

The dind entrypoint doesn't set `--tls=false` when starting up docker with tls disabled: https://github.com/docker-library/docker/blob/master/20.10/dind/dockerd-entrypoint.sh#L129

This causes slow start up now, and those logs indicate that it will not be functional in the future.

**Comment by tianon** [comment]
This is intentional behavior added by Docker upstream in order to discourage users from using plain-text TCP connections to the daemon (which can provide them with direct root access to the host, even with Docker-in-Docker). :confused:

I would not be comfortable with disabling this automatically against the wishes of the upstream project, and would provide the same recommendation as in #292 - the "correct" solution here is to adjust the command (and in this case, petition GitLab to allow adjusting that, because that seems like an oversight).

**Comment by acornax** [comment]
I am not asking to have it TLS be disabled automatically. I would just prefer for there to be a variety of functional ways to disable it explicitly. As I mentioned in #292, supplying `command` is not ideal for us.

I doubt that we'll be the only users to have issues switching to TLS, so I expect this will come up again.

**Comment by fredcooke** [comment]
@acornax not sure if this is best here or on #292 but mentioning it will show it on both sort of:

Why don't you simply build a derivative image that has the behaviour you need and publish it publicly and consume that in gitlab?

You don't have to use any container as is and I'd personally never use any public container as is without at the very least caching it under my own (or my org's) control with a FROM-only D-file arrangement. Never trust any upstream to not pull the rug out from under you by retagging. 

It was a MASSIVE failure in design to make images mutable in the first place, but that's the world we live in - trust no docker image, you will be burned sooner or later by:

Tag vanishes
New content for same tag (potentially malicious) 
Tag moves home to a new host/service eg gcr.io or quay.io or vice versa from there

If your infra (at any level) depends directly on images served from elsewhere then your infra is fragile by definition. 

End rant.

**Comment by tianon** [comment]
Unfortunately, this is as much as we're going to do here -- most CI platforms now allow adjusting the `command:` of services (and more full-featured orchestration systems like Kubernetes definitely do).
