### ISSUE TITLE
rootless add add propagation flag

### ISSUE THREAD

**Issue by mo-saeed** [docker-library/docker#299]
Hi,

Would be good to add this flag https://github.com/moby/moby/blob/master/contrib/dockerd-rootless.sh#L100 to rootlesskit arguments in https://github.com/docker-library/docker/blob/master/20.10/dind/dockerd-entrypoint.sh

**Comment by tianon** [comment]
There's some useful discussion in https://github.com/moby/moby/pull/40635 and also in https://github.com/docker-library/docker/pull/220 (where we tried to add this previously). :disappointed:

(TLDR, it's complicated :speak_no_evil:)

**Comment by tianon** [comment]
Going to close for now, but if this gets easier/possible for us to implement, a PR would be great. :smile:
