### ISSUE TITLE
Docker DIND 19.03.15, enable debug mode via environment varibales

### ISSUE THREAD

**Issue by prudhvigodithi** [docker-library/docker#300]
Hey everyone, I have recently started using docker dind image version 19.03.15, I'm trying to enable debug mode to see 
`time="2021-03-17T13:15:15.209381890Z" level=error msg="Handler for POST /images/create returned error: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"`
from the above error what container is being pulled, like the name of the container, however, I see I cannot add any docker options to the default 19.03.15 dind docker image, I see a few old tickets
https://github.com/docker-library/docker/pull/20 
https://github.com/docker-library/docker/pull/12/commits
Where we have an option to pass docker opts, but going through the new 19.03.15 DIND image I can't pass any extra docker options to the daemon, Any fix is there or an existing solution for my issue, please let me know.

We have an application that tries to pull an image from the internal docker registry, but when this application uses docker dind image, I get the above-mentioned timeout error going to outside docker registry, but when the same application uses host docker socket directly mounting from AWS ec2 installed docker socket works fine, so I wanted to enable debug mode on DIND image to further check the error.
Thank you

**Comment by tianon** [comment]
I'm not able to reproduce an issue supplying the `--debug` flag on 19.03: :confused:

```console
$ docker pull docker:19.03-dind
19.03-dind: Pulling from library/docker
Digest: sha256:fc6a078f81b3d99be498a5fc0f123191d3187653cab5632445240e8225ff6cf5
Status: Image is up to date for docker:19.03-dind
docker.io/library/docker:19.03-dind

$ docker run -it --rm --privileged docker:19.03-dind --debug
... 
DEBU[2021-03-22T21:04:29.236384082Z] Registering POST, /grpc                      
DEBU[2021-03-22T21:04:29.236434394Z] Registering GET, /networks                   
DEBU[2021-03-22T21:04:29.236492028Z] Registering GET, /networks/                  
DEBU[2021-03-22T21:04:29.236802152Z] Registering GET, /networks/{id:.+}           
DEBU[2021-03-22T21:04:29.236930562Z] Registering POST, /networks/create           
DEBU[2021-03-22T21:04:29.237046410Z] Registering POST, /networks/{id:.*}/connect  
DEBU[2021-03-22T21:04:29.237162293Z] Registering POST, /networks/{id:.*}/disconnect 
DEBU[2021-03-22T21:04:29.237279018Z] Registering POST, /networks/prune            
DEBU[2021-03-22T21:04:29.237366725Z] Registering DELETE, /networks/{id:.*}        
INFO[2021-03-22T21:04:29.237807213Z] API listen on [::]:2376                      
INFO[2021-03-22T21:04:29.237828473Z] API listen on /var/run/docker.sock           
```

**Comment by prudhvigodithi** [comment]
Hey @tianon, thanks for your prompt response, I'm running dind docker image on Kubernetes, adding `args: ["--debug"]` actually worked and enabled debug mode.
Thank you
