### ISSUE TITLE
linux/amd64 Images missing for 20.10.9* tags

### ISSUE THREAD

**Issue by benz0li** [docker-library/docker#333]
See https://hub.docker.com/_/docker?tab=tags&page=1&ordering=last_updated&name=20.10.9

**Comment by DBVK** [comment]
Please take a look at Jenkins pipeline: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/docker/
I think, fixing issue with space on executors should solve build issues.

**Comment by yosifkit** [comment]
Build server(s) are fixed now and the `docker:20.10.9` tags are updated with `amd64` images.
