### ISSUE TITLE
Request: Add s390x arch support

### ISSUE THREAD

**Issue by rohitsakala** [docker-library/docker#334]
When I look at the arch's supported by https://hub.docker.com/_/docker?tab=tags&page=1&ordering=last_updated, I don't see other arches like s390x. Can we add support for that too? Seems like it is being discontinued

**Comment by tianon** [comment]
Yep, this relies on Docker publishing official `s390x` releases, unfortunately.  Last I heard, IBM was working on something with them, but I don't think anything has come of it.

Our scripts still actively check for the IBM arches (as seen in the code below), so if they ever start showing up they'll automatically come back in our builds:

https://github.com/docker-library/docker/blob/8b8d62e7eb791b060cc75cb2956724a1bdc5484b/versions.sh#L14-L15
