### ISSUE TITLE
DIND Setup with DOCKER_CERT_PATH is using wrong files

### ISSUE THREAD

**Issue by sybnex** [docker-library/docker#335]
We are using DIND in a Kubernetes setup together with theia as webshell env. Therfore we have two pods running with a shared directory used for the Docker TLS setup.

Everything is working fine so far like, docker run/ps/exec/stop/rm/pull, etc. The only which is not working is the docker build command. The build commands try to reference to the ca.pem and key.pem in the ca and server directory instead of the "client" directory. Even if I try to setup the path specific with "tlscacert" and "tlskey" what could be wrong in this setup? Or is the build subcommand just using the wrong files?

`docker version
Client:
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc90bacf19bdbe37fd13eec8772432aca99
 Built:             Tue Oct  5 13:21:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:07:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

`docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
a0d0a0d46f8b: Pull complete 
Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest`

`docker build -t test .
error checking context: 'no permission to read from '/home/project/.tls/ca/key.pem''.`

`tree -p .tls/
.tls/
├── [drwxr-xr-x]  ca
│   ├── [-rw-r--r--]  cert.pem
│   ├── [-rw-r--r--]  cert.srl
│   └── [-rw-------]  key.pem
├── [drwxr-xr-x]  client
│   ├── [-rw-r--r--]  ca.pem
│   ├── [-rw-r--r--]  cert.pem
│   ├── [-rw-r--r--]  csr.pem
│   ├── [-rw-r--r--]  key.pem
│   └── [-rw-r--r--]  openssl.cnf
└── [drwxr-xr-x]  server
    ├── [-rw-r--r--]  ca.pem
    ├── [-rw-r--r--]  cert.pem
    ├── [-rw-r--r--]  csr.pem
    ├── [-rw-------]  key.pem
    └── [-rw-r--r--]  openssl.cnf

3 directories, 13 files`

`docker --tls --tlscacert .tls/client/ca.pem --tlskey .tls/client/key.pem --tlscert .tls/client/cert.pem build -t test .
error checking context: 'no permission to read from '/home/project/.tls/ca/key.pem''.`

**Comment by wglambert** [comment]
The error is really `error checking context: 'no permission to read from . . .` 

I'm assuming you're running as non-root or something very interesting is going on there. I've created a little example to show that even if the file isn't directly referenced, because it's in the build context Docker wants to see it and errors when it can't
```console
~ $ ls -l
total 4
-rw-r--r--    1 rootless rootless        30 Nov  9 19:16 Dockerfile
-rw-------    1 nobody   nobody           0 Nov  9 19:11 no-permissions-file
-rw-r--r--    1 rootless rootless         0 Nov  9 19:16 valid-file

~ $ cat Dockerfile
FROM alpine
COPY valid-file /

~ $ whoami
rootless

~ $ docker build . -t test
error checking context: 'no permission to read from '/home/rootless/no-permissions-file''.
```

So even though it just needed to copy `valid-file`, because `no-permissions-file` was in the build context it errored

**Comment by yosifkit** [comment]
I think a `.dockerignore` might work, but if it doesn't, then the other solution is to not use that directory as the build context.

**Comment by sybnex** [comment]
OK, that is really weird. And you are right. If I change that dir, then everthing is working. I wasn't expecting docker is checking every dir in the actual context for permissions. 

For everybody outside: just change the dir or move the certs for a situation like this.
