### ISSUE TITLE
No matching manifest for os/arch in the manifest list entries for 20.10.11* tags

### ISSUE THREAD

**Issue by benz0li** [docker-library/docker#337]
![no-matching-manifest](https://user-images.githubusercontent.com/20233085/142357661-c813e88a-9986-4fd6-b898-ce74cbec3519.png)

**Comment by christian98** [comment]
Same problem here. It seems only images for arch `linux/arm64/v8` were published.

**Comment by vyckou** [comment]
yes docker:20.10.11 is missing image
```
~ docker pull docker:20.10.11
20.10.11: Pulling from library/docker
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by tianon** [comment]
The official images build queue is unfortunately still very full from the backlog of https://github.com/docker-library/official-images/pull/11308, which is the reason this tag isn't built for `linux/amd64` just yet.  It should be happening soon (I've just move it to the front of the queue).
