### ISSUE TITLE
Windows Server 2022 LTS image

### ISSUE THREAD

**Issue by jpisciotto** [docker-library/docker#346]
Looking for the Windows Server 2022 LTS image.

**Comment by tianon** [comment]
Good catch; https://github.com/docker-library/docker/pull/347 :+1:

**Comment by jpisciotto** [comment]
> Good catch; #347 👍

I guess not many people trying to use the Docker image on Win22 :grin:

**Comment by tianon** [comment]
Yeah, given it's only the client (and really only can be), the use cases
for it are pretty limited.
