### ISSUE TITLE
docker:20.10-curl [Suggestion]

### ISSUE THREAD

**Issue by gabriel-astapenco** [docker-library/docker#348]
It would be nice to have a docker:20.10-curl image, like the -git version that we already have.

In my case, after building some docker images I always need to trigger pipelines or track the built version by using curl.
I'm sure more people do the same as me and also much more, installing and using curl in this image.
So, it would be nice to have an oficial docker:20.10-curl official image, me and much more people would make a good use of it.

**Comment by tianon** [comment]
The reason the `git` variant exists is not because `git` is convenient, but because you can `docker build <git-repo-url>` and the Docker client will invoke `git`, but it's big enough that we didn't want to include it in the default client variant.
