### ISSUE TITLE
Publish new images (golang 1.16.12 security vulnerabilities)

### ISSUE THREAD

**Issue by apj0nes** [docker-library/docker#354]
Docker images pushed to dockerhub contain application's built from golang 1.16.12 (which contains security vulnerabilities).
Would it be possible to get some updated images pushed with the patched golang version.

**Comment by tianon** [comment]
Unfortunately, just publishing new images won't actually change anything -- what you're looking for is all the underlying binaries being rebuilt.  Once there's a new 20.10.x release that includes https://github.com/moby/moby/pull/43326, this repository will be updated to it.
