### ISSUE TITLE
Multi-arch support

### ISSUE THREAD

**Issue by ozbillwang** [docker-library/docker#357]
currently the official image `docker` only support two architectures

<img width="694" alt="image" src="https://user-images.githubusercontent.com/8954908/162609756-9e8acfc5-c04b-4d45-94c0-4874c3ca8f57.png">

could we have more supported, similar as `hello-world`?

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8954908/162609772-292ed203-de37-4d11-ad77-2e6658991607.png">

**Comment by yosifkit** [comment]
We only support what is published on https://download.docker.com/linux/static/stable/.

As for the published `arm32v6` and `arm32v7` binaries, they have been broken for a while https://github.com/docker-library/docker/issues/260.

**Comment by ozbillwang** [comment]
sure, can we add the rest which are not broken?

[aarch64/](https://download.docker.com/linux/static/stable/aarch64/)
[armel/](https://download.docker.com/linux/static/stable/armel/) - Done, right?
[armhf/](https://download.docker.com/linux/static/stable/armhf/) - Done, right?
[ppc64le/](https://download.docker.com/linux/static/stable/ppc64le/)
[s390x/](https://download.docker.com/linux/static/stable/s390x/)
[x86_64/](https://download.docker.com/linux/static/stable/x86_64/) - Done, right?

**Comment by tianon** [comment]
Dig into each of those folders and you'll see that many are mising the 20.10 builds. :disappointed:

**Comment by tianon** [comment]
You can also see this reflected the 18.06.3 tags:

```json
$ docker manifest inspect docker:18.06.3-dind
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2404,
         "digest": "sha256:65df464ebcddd216ed4bb5d64c05a25b868790e1c3b51d3837cb2540dc235af9",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2404,
         "digest": "sha256:22906251738d48bb2024487558cde61a228409f2f58355b381a9df9457572b1f",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v6"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2404,
         "digest": "sha256:2e3218be044d44d12286493f231b163cc967db74f4fb2911437b001053e4769d",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2404,
         "digest": "sha256:4a186f2c0c447358853e73c1b4e94364efd4d3f9514a54a3b15ebe24b7fae9c5",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2404,
         "digest": "sha256:eb18c24eb0bee8cc207a5001ae0ac909ebb70547ffb37b34988ade6eb5e3ab6a",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by ozbillwang** [comment]
@tianon 

So from now on, the image will not support other arch any more?

**Comment by tianon** [comment]
The images as currently published already support as many architectures as Docker, Inc publishes official (working+static) builds for, so there's really not much more to do here (we're tracking the non-working arm32 binaries in #260).

Older versions have more supported, working architectures than newer ones do.  If that "supported architectures" matrix ever changes (with new binaries under https://download.docker.com/linux/static/stable/), we'll auto-include them:

https://github.com/docker-library/docker/blob/034e1d03eaf2c35ce4a21c4a4b621e2d2174b62e/versions.sh#L6-L12
