### ISSUE TITLE
Weird behavior in ECS

### ISSUE THREAD

**Issue by joumenharzli** [docker-library/docker#358]
Hello,

I am not sure if this is a bug or a misconfiguration from my side, but I was able to do a privilege escalation using this scenario.

I have an ECS service that’s running a container based on docker:dind image and has aws cli installed.
I created a Dockerfile in the running container

```
FROM amazon/aws-cli

RUN cat /etc/passwd

RUN aws sts get-caller-identity; \
        aws configure list
```

Then i launched 

```
bash-5.1# aws sts get-caller-identity

{    "UserId": "xxxx",
    "Account": "xxxx",    "Arn": "arn:aws:sts::xxxx:assumed-role/xxx-service-task-role/xxxxxxx"}
```

Here i have access to the correct role, **xxx-service-task-role**, assigned to the ECS service but when I build the image using the created Dockerfile i will be assigned the cluster role, and i even got access to the file /etc/passwd of the EC2 instance of the cluster
```

bash-5.1# docker build --no-cache .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM amazon/aws-cli ---> f6fcf76abde0
Step 2/3 : RUN cat /etc/passwd
 ---> Running in 997934416fe1
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
Removing intermediate container 997934416fe1
 ---> 530bcb2046f7
Step 3/3 : RUN aws sts get-caller-identity;     aws configure list
 ---> Running in dcc79114e808
{
    "UserId": "xxxx",
    "Account": "xxxx",
    "Arn": "arn:aws:sts::xxxxx:assumed-role/xxxx-cluster-role/xxxx"
}
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************WXYZ         iam-role
secret_key     ****************zyB7         iam-role
    region                eu-west-1             imds
Removing intermediate container dcc79114e808
 ---> 423f99b2f661
Successfully built 423f99b2f661
```

Here I got access to the cluster role **xxxx-cluster-role** and the EC2 file system, i was able to breakout from my container, does anyone have an idea about the issue and what configuration is missing in order to avoid this breakout ?

**Comment by wglambert** [comment]
This is because of the `privileged` mode that the Docker-in-Docker container requires which gives the container the same capabilities as the host https://containerjournal.com/topics/container-security/why-running-a-privileged-container-is-not-a-good-idea/

https://github.com/docker-library/docs/tree/master/docker#start-a-daemon-instance
>Note: `--privileged` is required for Docker-in-Docker to function properly, but it should be used with care as it provides full access to the host environment, as explained [in the relevant section of the Docker documentation](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities).

**Comment by joumenharzli** [comment]
Okay Thank you for your explanation.
