### ISSUE TITLE
Is there a way to get Alpine 3.4?

### ISSUE THREAD

**Issue by AndreKR** [docker-library/docker#36]
I cannot work with Alpine 3.5 because of https://bugs.alpinelinux.org/issues/6628.

Can I somehow pull an old image? Even the tags for older Docker version (`docker:1.11`) have been updated to Alpine 3.5.

**Comment by tianon** [comment]
Yeah, we got a little overzealous :disappointed: 

I've opened https://github.com/docker-library/docker/issues/37 to revert this for 1.11 and 1.12.

See https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for further discussion on this issue.
