### ISSUE TITLE
proposal: custom dockerd port

### ISSUE THREAD

**Issue by stuart-warren** [docker-library/docker#370]
Hi, 

I'd like to run dind on a different port so I can make it work with host networking within gitlab-ci

Adding `--host=tcp://0.0.0.0:2378` as the image command doesn't work due to still trying to listen on 2376 which is already taken.

I have a custom version of the dind image which works for us.

Would you be open to a PR to configure the port via environment variables?

eg

```sh
DOCKER_LISTEN_PORT_TLS="${DOCKER_LISTEN_PORT_TLS:-"2376"}"
DOCKER_LISTEN_PORT_HTTP="${DOCKER_LISTEN_PORT_HTTP:-"2375"}"
```

**Comment by yosifkit** [comment]
We'd rather not add any more customization points to the entrypoint scripts. You can just skip the `dockerd-entrypoint.sh` script (`--entrypoint dockerd`) and it will be as customizable as needed.
