### ISSUE TITLE
Question: how do you generate versions.json?

### ISSUE THREAD

**Issue by TonyPythoneer** [docker-library/docker#372]
I noticed this file but I don't know how to search its keyword.

https://github.com/docker-library/docker/blob/master/versions.json

I want to know how you generate it. Thanks!

**Comment by TonyPythoneer** [comment]
The answer is here.
https://github.com/docker-library/docker/blob/a5154f6c2a1201211ae8792dcf1d4956439597db/generate-stackbrew-library.sh

**Comment by yosifkit** [comment]
`versions.json` is generated by [`versions.sh`](https://github.com/docker-library/docker/blob/5bda34eeb02386173b6e298cb4a983783efc7e8d/versions.sh#L276).

`generate-stackbrew-library.sh` just uses the content of `versions.json` and the state of the repo to generate a [docker-library/official-images](http://github.com/docker-library/official-images) RFC2822 "library" file.
