### ISSUE TITLE
Device "ip_tables" does not exist on Alpine Linux

### ISSUE THREAD

**Issue by henriquehbr** [docker-library/docker#374]
I'm trying to run a [docker-in-docker (dind)](https://hub.docker.com/_/docker) (more specifically, `docker:22.06.0-beta.0-dind-rootless`) image on a Alpine Linux host, that is running inside VirtualBox, whenever the container starts up, it fails to launch the Docker inside the container, with the following error message:

```
Signature ok
subject=CN = docker:dind client
Getting CA Private Key
Device "ip_tables" does not exist.
modprobe: can't change directory to '/lib/modules': No such file or directory
open: No such file or directory
[rootlesskit:child ] error: executing [[ip tuntap add name tap0 mode tap] [ip link set tap0 address ...]]: exit status 1
```

I've figured out that the problem is not on VirtualBox part, as this error didn't happened on an Arch Linux host, so it's specific to Alpine

As Docker uses the host kernel, i've tried enabling it through `modprobe ip_tables`, but the same error persisted, is there any package that enables these kernel modules on the system, or it's something else that i'm missing?

**Comment by wglambert** [comment]
Similar to https://github.com/docker-library/docker/issues/350#issuecomment-1017021899

https://github.com/rootless-containers/rootlesskit/issues/69#issuecomment-506813393 seems relevant
>iproute2 installed as the busybox `ip` doesn't support tuntap

**Comment by henriquehbr** [comment]
Sorry for the delay, even after installing `iproute2` and ensuring that the `ip` binary being executed belongs to it, the same error occurs

I think it's also worth mentioning that `docker:22.06.0-beta.0-dind-rootless` already installs `iproute2`, so it shouldn't be necessary to manually install it when using this image as a base

---

By the way, do you know if the `modprobe` error messages above have anything to do with the container failing to execute, or this problem is solely due to the `ip` command?

**Comment by tianon** [comment]
I'm not able to reproduce a failure with that image (running on Debian Bullseye) -- my best guess is that maybe your host kernel is missing tun/tap support or something?

**Comment by henriquehbr** [comment]
You're right, i've checked if Alpine kernel [config](https://git.alpinelinux.org/aports/tree/main/linux-lts/lts.x86_64.config) includes support for tun/tap, and `CONFIG_TUN` is included as a module, so running `modprobe tun` solved the problem

Thanks a lot! @tianon @wglambert

**Comment by WhyNotHugo** [comment]
I just hit the same issue. Aside from installing `iproute2`, I needed to load another module: `modprobe iptable_nat`.
