### ISSUE TITLE
No manifests for 20.10.18* tags

### ISSUE THREAD

**Issue by benz0li** [docker-library/docker#376]
![20 10 18_no_manifests](https://user-images.githubusercontent.com/20233085/189580709-e6dbca62-3a1c-4fa5-bd47-364e60317e00.png)

**Comment by johnthagen** [comment]
We also came here looking for a `20.10.18` `docker` image, hoping to be able to use Compose 2.10.2.

**Comment by yosifkit** [comment]
[See a change merged here that doesn't show up on Docker Hub yet?](https://github.com/docker-library/docker/tree/c13cbee1cfd9d7582f7b2e9f958cf24e39b64715#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet) -> so, https://github.com/docker-library/official-images/pull/13127.

---

Docker compose 2.10.2 is already in the current images: https://github.com/docker-library/docker/commit/46a5fa097f8b9995cdab2270f0ffa623c243c3d2, https://github.com/docker-library/official-images/pull/13051.
