### ISSUE TITLE
Update buildx plugin to v0.10.0

### ISSUE THREAD

**Issue by z0rc** [docker-library/docker#391]
https://github.com/docker/buildx/releases/tag/v0.10.0

I noticed, that compose plugin updates are performed by @docker-library-bot in automated manner. But as week passed since buildx release, and there is no automated update, I decided to raise this issue.

**Comment by tianon** [comment]
Scraping issue fixed in 4d1d884a47c011987bc530e4a9418c8d710aa0ae, version updated in 5ecac9af14c03e24685e478f1c8ddd7f156883d4 & 03089085068a23c0c5c423331093640dfeecac63 :bow:

Thanks for the prod! :+1:
