### ISSUE TITLE
Add OCI image annotations to docker hub published docker images

### ISSUE THREAD

**Issue by candrews** [docker-library/docker#392]
The images published to https://hub.docker.com/_/docker do not have [OCI image annotations](
https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys), such as `org.opencontainers.image.source`

These annotations are useful for people to manual use as well as for use by tools. For example, [Snyk uses them in its UI](https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/) and [Renovate uses them to find release notes](https://github.com/renovatebot/renovate/blob/34.115.1/lib/modules/datasource/docker/readme.md).

I believe at least these labels should be added to the images:
* `org.opencontainers.image.source`
* `org.opencontainers.image.revision`

**Comment by tianon** [comment]
See https://github.com/docker-library/cassandra/issues/260 for a recent place where this was discussed on another of the Official Images.

**Comment by tianon** [comment]
https://explore.ggcr.dev/?image=docker:24.0.7-dind@sha256:c90e58d30700470fc59bdaaf802340fd25c1db628756d7bf74e100c566ba9589 (this is fixed)
