### ISSUE TITLE
Facing issue with image `docker:dind`

### ISSUE THREAD

**Issue by aashish-fiftyfive** [docker-library/docker#396]
We are facing issues with image `docker:dind` which gives error - `ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` but when we use older one like `docker:20-dind` it works absolutely fine

**Comment by pallasathena92** [comment]
I have the same question, and I tried docker:20-dind as you said, it didn't work either. Could you mind share your Dockerfile?

Here is my Dockerfile:
`FROM docker:20-dind

RUN apk update
#RUN curl -sSL https://get.docker.com/ | sh

WORKDIR /test
COPY test .`

**Comment by aashish-fiftyfive** [comment]
The issue was related to `dockerd -H tcp://0.0.0.0:2375` which I set in kubernetes manifest, I removed it and it got worked.

**Comment by tianon** [comment]
Nice, glad you got it solved - so this can be closed?

**Comment by pallasathena92** [comment]
@tianon I didn't set any host in my Dockerfile. If I understand correct, I build a docker base on docker:find can't use docker-in-docker directly?
if I need to add more config or other things, what do I need to add?

**Comment by jared-mackey** [comment]
Also running into issues with `dind` that I don't have on `20-dind`. Using this as a Gitlab CI runner. Getting this error either at the end of a `docker build` or at `docker push` to the gitlab registry. Hard to tell without adding more debug logging which one it is.

```
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
```

**Comment by tianon** [comment]
That error sounds like it might be related to https://github.com/moby/buildkit/issues/3576

**Comment by yosifkit** [comment]
@pallasathena92 Are you talking about running a `dockerd` server from within a `RUN` line in a Dockerfile? That's possible, but incredibly complex and not something we recommend.

**Comment by hetpats** [comment]
> The issue was related to `dockerd -H tcp://0.0.0.0:2375` which I set in kubernetes manifest, I removed it and it got worked.

ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

We have the exact issue and we are not setting the manifest as @aashish-fiftyfive , the container runs in privileged mode and is allowed to escalate privileges. I did find that putting a pause in the CI pipeline after the dind  container is up helped resolve this issue, may be its a race condition where dockerd doesn't startup fast enough?

**Comment by hetpats** [comment]
@chadlwilson 
I was able to confirm this bug i added a ps -ef  followed by sleep of 15 sec and then a ps -ef again in my CI stage before execution steps.
Consistently found that when we get the error in pipeline complaining about  "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"   dockerd isn't started causing above failure from our CI pipeline.

Here is output when the CI pipeline with ps -ef immediate to container being available on kubernetes cluster and CI pipeline starting its job on it. If i dont have the sleep command i cannot ensure dockerd will start before my CI starts execution of commands on the container.

PID      USER.     TIME COMMAND
1         root         0.00  {docker-encrypto} /bin/sh  /usr/local/bin/dockerd-entrypoint.sh
12       root         0.01 openssl genrsa -out /certs/server/key.pem 4096
25.     root         0.00 ps -ef

After this i have a sleep of 15 sec followed by ps again ..

PID      USER.     TIME COMMAND
1         root         0.00  dockerd-init --dockerd --host=unix///var/run/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem
78      root          0.00 dockerd --host=unix///var/run/docker.sock  --host=tcp://0.0.0.0:2376 --tlsverify --tlscert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem
91.     root          0.00  continerd --config /var/run/docker/cotainerd/containerd.toml --log-level info
111     root          0.00   sleep 3
112    root          0.00   ps -ef

**Comment by chadlwilson** [comment]
@hetpats Well in your case it seems it's using TLS auth so it won't be sleeping 15s as referred earlier.

In either case, I don't think it's a bug. AFAIK with the default container entrypoint the daemon starts synchronously during the entrypoint so it should be started before anything considers the container to be ready. If you are customising the image/entrypoint such that the daemon starts in the background/async along with other processes, it would be your responsibility to make sure the daemon is started before it is needed by other processes in the container.
