### ISSUE TITLE
No longer creating /.dockerenv with version 23

### ISSUE THREAD

**Issue by paddy-hack** [docker-library/docker#399]
I am using a script that checks for the presence of `/.dockerenv` to decide whether auto-removing packages makes sense (for some definition of sense :wink:).  This has worked fine with Docker Engine 20.10.x and GitLab CI/CD using the `docker:20-cli` image and a `docker:20-dind` service.

Upgrading to Docker Engine 23.0.0, I still see `/.dockerenv` when running things locally.  However, my GitLab CI/CD job no longer sees a `/.dockerenv` file when using `docker:23-cli` with a `docker:23-dind` service.  What happened?

FYI, I'm using a self-hosted GitLab Runner 15.8.1 using the Docker executor.  
BTW, the same issue is present when using GitLab Runner 15.7.1.

**Comment by tianon** [comment]
Hmm, I'm guessing your CI job is running `docker build`?  One of the major changes in 23.0 is that `docker build` now defaults to using BuildKit, and I'm not sure whether it creates the `.dockerenv` file (so that could explain why your locally run containers still see it, but a `RUN` line in a `Dockerfile` might not).

**Comment by paddy-hack** [comment]
The CI job runs `docker build` indeed and the fact my script doesn't see a `/.dockerenv` under 23.0 would indicate that BuildKit doesn't create it.

At least I have something to go on now and will check 20 *with* BuildKit and 23 *without* it (probably over the weekend).  That aside, what would be the prefered way to check whether you're in a container during a `docker build`?

**Comment by tianon** [comment]
I think https://github.com/genuinetools/amicontained is probably useful, although I'm not sure if it detects this case.  Realistically, you're not _supposed_ to be able to detect that you're contained (or how you're contained), but the abstraction is leaky in practice (as you discovered, relied on, and now have been broken by :grimacing: :sweat_smile:).

**Comment by paddy-hack** [comment]
I created a (temporary) project over a GitLab.com to test versions 20 and 23 with `DOCKER_BUILDKIT` turned on and off.  The [build results](https://gitlab.com/paddy-hack/docker-env-check/-/pipelines/775016202/builds) (for as long as the project stays around) show that BuildKit does *not* create `/.dockerenv` in either version.  Without BuildKit, the file is created by both versions.

Running a local build without BuildKit on Docker 23.0, I see
``` console
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```
so I had better install `docker-buildx-plugin` unless I want to become obsolete :sweat_smile:

**Comment by paddy-hack** [comment]
Back to me wanting to do things differently in a script depending on whether the script is run in a container or not, even though it's not supposed to be able to notice, is there a way it can?  I don't fancy installing `amicontained` just for that.

If not, it is not a really big deal and I can find some other way to work around things, e.g. setting an environment variable for the Dockerfile's `RUN`  command that runs the script.

BTW, the use case is one where the script migrates Debian to Devuan.  The clean up scenarios differ between containers and host.  For reference, I'm using [this cleanup code](https://git.devuan.org/paddy-hack/container-images/src/commit/29d8c2bf7fbb7e7894b902000c59b4b004de3a4f/migrated/migrate.sh#L139-L157) at present.  It is mostly used to migrate the slim variant of your Debian images to Devuan, before I use the migrated image to build Devuan images from scratch :wink:

**Comment by paddy-hack** [comment]
I've modified my [cleanup code](https://git.devuan.org/paddy-hack/container-images/src/commit/046648a8354f216d1b8a31dab1d0779ae0ea8673/migrated/migrate.sh#L139-L157) to check for a `/.dockerenv` file first and a `$dockerenv` environment variable next.  In the `Dockerfile` we can be assured of running in a Docker environment so `RUN` command sets the variable.

Now all is well again for me.  Builds run as intended both under 20.x and 23.x.  At the same time, I can still test the script using a `docker run` or to migrate a machine, virtual or not.

**Comment by paddy-hack** [comment]
Should this issue be retitled (because it is really BuildKit that is the culprit) and closed (because I rely on undocumented (really?) behaviour)?

If so, please feel free to do so yourself ... or ask me, nicely :stuck_out_tongue_winking_eye:

**Comment by tianon** [comment]
I think we're OK to just close it -- glad you managed to figure out a solution for your use case. :+1:
