### ISSUE TITLE
docker:23.0.1-dind for linux/amd86 missing

### ISSUE THREAD

**Issue by shulcsm** [docker-library/docker#404]
```
docker pull docker:23.0.1-dind
23.0.1-dind: Pulling from library/docker
no matching manifest for linux/amd64 in the manifest list entries
```
https://hub.docker.com/_/docker/tags?page=1&name=23.0.1-dind

I'm not sure how CI works, but this action completed 8 hours ago:
https://github.com/docker-library/docker/actions/runs/4139535595

**Comment by MatthijsKok** [comment]
`docker:23.0.1` (no `-dind`) also has this issue.

**Comment by vitoyucepi** [comment]
I think the amd64 builder node is stuck since this build https://doi-janky.infosiftr.net/job/multiarch/view/triggers/job/amd64/job/_trigger/42242/ because there's no space left.
There will be no new builds until someone figures out how to clean it up.

**Comment by yosifkit** [comment]
> java.io.IOException: No space left on device

:facepalm: 

Somehow the `amd64` builder ran out of space unexpectedly. We are working to fix it and get the builds going.

**Comment by tianon** [comment]
Should be fixed now :+1:
