### ISSUE TITLE
Error "Device "ip_tables" does not exist."

### ISSUE THREAD

**Issue by mo-saeed** [docker-library/docker#412]
Hello, 

I upgraded my docker file (dind-rootless) to have the latest docker version "23.0.1" (upgraded from 20.10) but then I get this error.

the dockerd-entrypoint.sh seems to continue working and all good but I am wondering if this error has any impact on docker operations

```
/certs/client/cert.pem: OK
Device "ip_tables" does not exist.
ip_tables              32768  5 iptable_filter,iptable_security,iptable_raw,iptable_nat,iptable_mangle
x_tables               45056  22 ebtables,ip6table_filter,xt_conntrack,xt_statistic,iptable_filter,iptable_security,nft_compat,xt_multiport,xt_tcpudp,xt_addrtype,xt_nat,xt_comment,xt_owner,xt_set,ip6_tables,ipt_rpfilter,iptable_raw,ip_tables,ip6table_mangle,xt_MASQUERADE,iptable_mangle,xt_mark
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.4.0-1094-azure
```

I am using azure AKS and docker rootless is running on debian-slim.

**Comment by mo-saeed** [comment]
@tianon I would appreciate your advice here.
Thanks a lot!

**Comment by tianon** [comment]
I think this is probably https://github.com/docker-library/docker/pull/437#issuecomment-1845920765

**Comment by piyush-bhuwalka** [comment]
@mo-saeed We are getting this issue on docker:dind image

ip: can't find device 'nf_tables'

whats the resolution ?

**Comment by tianon** [comment]
Fixed by https://github.com/docker-library/docker/pull/465 which will be updated by https://github.com/docker-library/official-images/pull/15921 :+1:
