### ISSUE TITLE
Install slirp4netns in dind rootless image

### ISSUE THREAD

**Issue by tgreeve** [docker-library/docker#420]
When doing docker build in docker:dind-rootless, there is a strange problem which resolving github.com returns NXDOMAIN. 

https://github.com/alpinelinux/docker-alpine/issues/155

I encounter this problem in both K8S (EKS 1.23) container and MacOS Docker-Desktop (4.17.0). The problem can be resolved by replacing vpnkit with slirp4netns as the network bridge. However, slirp4netns binary isn't installed in the latest version of docker:dind-rootless image. 

Is it possible to do a apk add  slirp4netns in dind-rootless build?

**Comment by tianon** [comment]
Duplicate of https://github.com/docker-library/docker/pull/274

**Comment by tgreeve** [comment]
Thanks, seemingly the CVEs and license issues prevent slirp4netns from being included in dind-rootless image.
