### ISSUE TITLE
With docker 24-dind image, GRPC stopped resolving DNSes

### ISSUE THREAD

**Issue by jacek-jablonski** [docker-library/docker#428]
Hi,
I'm using a `dind` image in conjunction with github-runner-controller. After updating to version **24** of the `dind` image, GRPC stopped being able to resolve DNS if it uses c-ares for resolving (native resolving still works).

```
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 DNS resolution failed for secretmanager.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=A name=secretmanager.googleapis.com is_balancer=0: Could not contact DNS servers
```

On the previous version **23** everything works as it should (both c-ares and native).

What could be the cause of such behavior?

**Comment by tianon** [comment]
I think this might be related to https://github.com/moby/moby/issues/45553, https://github.com/moby/moby/issues/45555, https://github.com/moby/moby/pull/45565 :eyes:

**Comment by tianon** [comment]
Would you be interested in/willing/able to test against `tianon/docker-master@sha256:77b83fd786f78a5361819cc4732df187c8f3c02a39fc9fdaaf4a1fd5ad81fbe8` (which includes https://github.com/moby/moby/pull/45565) to help verify?

**Comment by jacek-jablonski** [comment]
@tianon this works fine 👍🏻

**Comment by tianon** [comment]
Nice, thanks for testing/confirming!  That was backported to the 24.x branch in https://github.com/moby/moby/pull/45573, so will be in the upcoming 24.0.1 :bow:

**Comment by tianon** [comment]
Should be fixed via https://github.com/docker-library/docker/commit/d5357e5 -> https://github.com/docker-library/official-images/pull/14699 :+1:
