### ISSUE TITLE
No AMD64 Build for 24.0.2-dind

### ISSUE THREAD

**Issue by jonasled** [docker-library/docker#429]
Hi,
I wanted to switch to the new Docker dind 24.0.2, but on the docker hub is only a image for ARM64 pushed.

**Comment by yosifkit** [comment]
Short answer: some architectures finish faster than others (or happen to trigger sooner). The index will be updated as other finish.

Longer: https://github.com/docker-library/docker/tree/679ff1a932a1bdf4341fb0d5cb06f088c77d44bf#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
