### ISSUE TITLE
Reg: harbor container registry config in dind

### ISSUE THREAD

**Issue by shan100github** [docker-library/docker#431]
hi,
I am using `docker:23.0.1-dind` with `dockerd-entrypoint.sh --tls=false --log-level=info ` as an entry point of the container.

I tried adding  --insecure-registry and while trying `docker login` ended with `Error response from daemon: Get "https://<ip>/v2/": x509: cannot validate certificate for <ip> because it doesn't contain any IP SANs`

I tried enabling https in the harbor and passed on cert files to `/etc/docker/certs.d/<ip>:443`  even then failed with the same cert error up on `docker login` 

Following is the process I can see in my container.
```
   16 root      0:00 dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --tls=false --log-level=debug --insecure-registry <ip>:443
   74 root      0:01 containerd --config /var/run/docker/containerd/containerd.toml --log-level debug
```

I would like to know how to access private registry in the dind container.
Also, do we need to pass custom containerd.toml  file ?

**Comment by tianon** [comment]
Try using _just_ `--insecure-registry <ip>` (ala, no port).

(In my experience, that setting is a bit fiddly to get right :sob:)

**Comment by shan100github** [comment]
- Created self-signed certificate and added in `/etc/docker/certs.d/<ip>/` 
- `sudo openssl genrsa -out client.key 4096`
- `sudo  openssl req -new -x509 -text -key client.key -out client.cert`
- Added daemon.json with insecure-registry 

These steps resolved to access the private registry.
