### ISSUE TITLE
dind-rootless (v20.10.6): Container start hangs when multiple dind instances are running on the same host

### ISSUE THREAD

**Issue by iarkhanhelsky** [docker-library/docker#432]
Hi! 

In our setup we run multiple Docker-in-Docker instances per host. We now evaluating dind-rootless image and encountered an issue which I'll try to explain below:

- We run dind on GKE (k8s) clusters with [cos_containerd](https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd) image. 
- On each host we allocate 16 pods with dind-rootless image 
- When all 16 pods are ready running the docker container inside any of them infinitely hangs:

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
719385e32844: Pull complete
Digest: sha256:a13ec89cdf897b3e551bd9f89d499db6ff3a7f44c5b9eb8bca40da20eb4ea1fa
Status: Downloaded newer image for hello-world:latest
^C^C^C^C
```

When the pod is being killed we can observe the following error:
```
ERRO[0049] error waiting for container:
docker: error during connect: Post "https://localhost:2376/v1.41/containers/82b5f2e72a553bfc49fe7460308a363c97bf8139350706da721af864b752fa71/start": EOF
```

`dockerd` log doesn't show anything suspicious expect the following line:
```
time="2023-06-28T09:35:50.406776317Z" level=debug msg="sandbox set key processing took 87.898635ms for container f40a04583de816fe0ae1d233194d774353fbcd942a713a53f4dfe08888ffef19"
time="2023-06-28T09:35:58.486678825Z" level=debug msg="Calling POST /v1.41/containers/f40a04583de816fe0ae1d233194d774353fbcd942a713a53f4dfe08888ffef19/kill?signal=WINCH"
time="2023-06-28T09:35:58.486755879Z" level=debug msg="Sending kill signal 28 to container f40a04583de816fe0ae1d233194d774353fbcd942a713a53f4dfe08888ffef19"
```

The issue seems to be fixed between `20.10.6` and `20.10.24` image versions. But I can't find changelog entry that would explain it directly. 

Could you help me figure out the root cause of this issue? Thank you!

**Comment by tianon** [comment]
Version `.6` to `.24` is a really wide spread -- could you maybe bisect and narrow it down further? :sweat_smile:

**Comment by iarkhanhelsky** [comment]
Hi, I did the bisecting thing and based on my tests the issue is fixed in `20.10.7` (checked `.24`, `.15`, `.10`, `.8`). I also checked `.5` and it has a different issue on my setup. Even one pod per node causes the following error end exits:
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
719385e32844: Pull complete
Digest: sha256:a13ec89cdf897b3e551bd9f89d499db6ff3a7f44c5b9eb8bca40da20eb4ea1fa
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:352: getting the final child's pid from pipe caused: EOF: unknown.
ERRO[0002] error waiting for container:
```

**Comment by tianon** [comment]
That's helpful!  That means your fix is likely somewhere in https://github.com/moby/moby/releases/tag/v20.10.7 :eyes:

(f6a0c427f0354dcf5870c430c72c8f1d6b4e6d5e...279ba9c93e8e26a15171645bd511ea8476c4706e; the only relevant changes in the image between those tags was version bumps including updating `hack/dind` to the v20.10.7 changes)

**Comment by PAStheLoD** [comment]
Hello for everyone who ends up here after a few too many mystery EOFs!

on our CI we noticed these network hangs (~153 sec), using GitLab CI (DOCKER_TLS_CERTDIR: "" and --tls=false --dns=1.1.1.1 --experimental), and docker compose inside the CI job container with dind.

```
Container app-redis-1  Creating
Container mailpit  Creating
Container app-mongodb-1  Creating
Container app-mongodb-1  Created
Container app-redis-1  Created
Container app-redis-1  Starting
Container app-mongodb-1  Starting
Container mailpit  Starting
error during connect: Post "http://docker:2375/v1.51/containers/1eb1499f0e938e873631bc02b89e60298403b8f31b2353221392758b31fa4484/start": EOF
```

14:59:42 is the starting line, then 15:02:15 is the EOF (the image pulls also took pretty long due to an offline mirror)

and in some logs it's pretty visible that `dockerd` is still online (since as compose decides to tear down the stack it can without delays), and also adding a retry loop is a "workaround"

looking at the CI logs the pattern we noticed:


dind image | jobs | EOF rate | span
-- | -- | -- | --
docker:27.4.1-dind-rootless | 20 | 0% | Jun 21–23
docker:29.6.0-dind-rootless | 453 | 20.8% (94) | Jun 23 → Jul 4
docker:29.6.1-dind-rootless | 16 | 31.3% (5) | Jul 4
docker:29.6.1-dind (rootful) | 22 | 0% | Jul 4

CI_DEBUG_SERVICES: true did not show anything, so likely it's something in rootlesskit networking.

**Comment by yosifkit** [comment]
@PAStheLoD That kind of seems related to the removal of `vpnkit` and falling back to `slirp4netns` when 29.5.0 was added (https://github.com/docker-library/docker/pull/575). You could try `DOCKERD_ROOTLESS_ROOTLESSKIT_NET=gvisor-tap-vsock` and see if that works better.
