### ISSUE TITLE
Cannot pull 'docker' image

### ISSUE THREAD

**Issue by msander** [docker-library/docker#435]
Hi, we have problems pulling the docker image from docker hub. The problem first occurred yesterday.

```quote
docker pull docker:dind
Trying to pull repository docker.io/library/docker ... 
manifest for docker.io/docker:dind not found
```

I also tried different tags. Pulling other images works fine...

**Comment by yosifkit** [comment]
I am unable to reproduce today.
```console
$ docker pull docker:dind
dind: Pulling from library/docker
31e352740f53: Already exists
a909a6dccb2a: Pull complete
4f4fb700ef54: Pull complete
ee5d1d3b3c0a: Pull complete
5061ed9e3f18: Pull complete
97b5a3616403: Pull complete
6f429e55eceb: Pull complete
7288f1321468: Pull complete
39e34e641f8b: Pull complete
e6ee3b156fe6: Pull complete
98627b255aea: Pull complete
f191f06e12ea: Pull complete
6471e5d17b88: Pull complete
b911e1248ddc: Pull complete
Digest: sha256:25a7feece7050334e8bd478dc9b6031c24db7fe81b2665abe690698ec52074f2
Status: Downloaded newer image for docker:dind
docker.io/library/docker:dind
```

**Comment by msander** [comment]
The reason seems to be an old docker version (which comes with centos 7). 

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64

Maybe the build docker version changed? https://stackoverflow.com/questions/75384648/pull-from-docker-hub-returns-not-found-with-older-docker-version

**Comment by tianon** [comment]
Oof, yeah, maybe -- Docker 1.13 has been EOL for a _very_ long time. :see_no_evil:

**Comment by tianon** [comment]
For reference, this is probably because the images we publish are now OCI images: https://explore.ggcr.dev/?image=docker:dind (and I don't recall whether Docker 1.13 supported those yet or not, but it looks like maybe not)
