### ISSUE TITLE
Pull fails for dind:24.0.5-dind with a Unexpected EOF 

### ISSUE THREAD

**Issue by luroto** [docker-library/docker#439]
Hi there!
We have been working using the docker:24.0.5-dind since a week ago and we noted that starting from today our Kubernetes nodes (EKS 1.24 version) are not able to pull this image anymore:

![image](https://github.com/docker-library/docker/assets/47120090/2d563e01-6b2d-4b95-8e5d-3ae22a125baf)

We use ` nerdctl pull docker:24.0.5-dind` to test it manually from different nodes, and apparently it is only failing with different dind versions. What could be the issue here?

**Comment by tianon** [comment]
I can't reproduce: 🙈

```console
$ docker pull docker:24.0.5-dind
24.0.5-dind: Pulling from library/docker
7264a8db6415: Already exists 
110ac87b2a72: Pull complete 
4f4fb700ef54: Pull complete 
cb3b0f7713d7: Pull complete 
bbab7b71df77: Pull complete 
7115b760bf89: Pull complete 
fb33fbb55f1a: Pull complete 
30fbbdffb8e3: Pull complete 
55fb24f75fb0: Pull complete 
aabff4d636f8: Pull complete 
d75ebc365546: Pull complete 
d54b27304de7: Pull complete 
4b4b9734a564: Pull complete 
adc79f9020c0: Pull complete 
Digest: sha256:3c6e4dca7a63c9a32a4e00da40461ce067f255987ccc9721cf18ffa087bcd1ef
Status: Downloaded newer image for docker:24.0.5-dind
docker.io/library/docker:24.0.5-dind
```

I'm guessing this was probably a fluke / temporary outage of Docker Hub (or something in your nodes themselves that caused a bit of network flakiness).
