### ISSUE TITLE
`docker:dind` Standard Error/Output Format

### ISSUE THREAD

**Issue by JohnYoungers** [docker-library/docker#449]
We can modify the log to file behavior with the `log-driver` configuration, but is there a way to adjust the logs that are going to the output streams?

```
time="2023-09-29T20:15:20.748926661Z" level=info msg="Daemon has completed initialization"
time="2023-09-29T20:15:20.797217899Z" level=info msg="API listen on /var/run/docker.sock"
time="2023-09-29T20:15:20.797255584Z" level=info msg="API listen on [::]:2376"
```

Write as JSON for example?

**Comment by tianon** [comment]
I'm not actually sure -- I believe that the Docker daemon is using `logrus`, so those are structured logs, but I don't know whether the format is actually exposed / configurable (I'm not seeing anything obvious in `dockerd --help`).

**Comment by tianon** [comment]
Closing since this isn't something we can change in the image/packaging (it'd have to be a feature request for the Docker daemon itself).

**Comment by tianon** [comment]
Aha, see https://github.com/moby/moby/pull/45737 -- added in v25+!  Thanks @thaJeztah :heart:

**Comment by JohnYoungers** [comment]
Nice! Thank you for the follow-up @tianon !
