### ISSUE TITLE
Incorrect link in docker docs readme

### ISSUE THREAD

**Issue by JoshKellyVFX** [docker-library/docker#45]
Hey Guys, 

I've just noticed that the link on [this page](https://github.com/docker-library/docs/tree/master/docker#start-a-daemon-instance) links to nothing.

Specifically [this link](Note: --privileged is required for Docker-in-Docker to function properly, but it should be used with care as it provides full access to the host environment, as explained in the relevant section of the Docker documentation.) 

I see in the readme's they mention running ./update.sh but I don't see one in that folder. Should I just push a pull request for that file?

Thanks,
Josh

**Comment by JoshKellyVFX** [comment]
Oh and I plan on replacing it with [this link](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities), yes or no?

**Comment by yosifkit** [comment]
That seems good. Thanks!  Be sure to put the change in `docker/content.md` and then a bot will ensure `docker/README.md` and the Docker Hub get updated after merge.  `update.sh` is in the root of the docker-library/docs repo, but the bot will take care of running it.
