### ISSUE TITLE
Regression in docker-compose: can't set healthcheck.start_interval as feature require Docker Engine 1.25 or later

### ISSUE THREAD

**Issue by cjlarose** [docker-library/docker#473]
Recently, the image `docker:24.0.7` advanced from `sha256:ca9a56ffc0339a72cbf2beb7650f4423258f405520dcc7ac9af4858cfdc09fce` to `﻿sha256:63897b20cb7da770f94301070dafc902f43cacee189c71c15f6a21e7caeecda1`.

The following `docker-compose.yaml` file worked in the former release and fails in the latter release

```yaml
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "docker-healthcheck"]
      start_period: 30s
      start_interval: 1s
    image: postgres:13
```

The error message from `docker compose up` is 

```
﻿can't set healthcheck.start_interval as feature require Docker Engine 1.25 or later
```

Full command

```sh
docker run -it \
  -v /var/run/docker.sock:/run/docker.sock \
  -v "$PWD/docker-compose.yaml":/app/docker-compose.yaml \
  docker@sha256:ca9a56ffc0339a72cbf2beb7650f4423258f405520dcc7ac9af4858cfdc09fce \
  /bin/sh -c 'cd /app && docker compose up'
```

Returns

```
[+] Running 1/0
 ✔ Container app-postgres-1  Created                                                                          0.1s 
Attaching to postgres-1
postgres-1  | The files belonging to this database system will be owned by user "postgres".
postgres-1  | This user must also own the server process.
...
```

New release

```sh
docker run -it \
  -v /var/run/docker.sock:/run/docker.sock \
  -v "$PWD/docker-compose.yaml":/app/docker-compose.yaml \
  docker@sha256:63897b20cb7da770f94301070dafc902f43cacee189c71c15f6a21e7caeecda1 \
  /bin/sh -c 'cd /app && docker compose up'
```

Returns

```
[+] Running 0/0
 ⠋ Container app-postgres-1  Creating                                                                         0.0s 
can't set healthcheck.start_interval as feature require Docker Engine 1.25 or later
```

`buildx` and `compose` were both upgraded recently `docker:24.0.7`, so the regression might actually be in one of those projects.

Since I'm bind-mounting my docker socket from the host, `docker --version` on the host returns

```
﻿Docker version 24.0.5, build v24.0.5
```

**Comment by tianon** [comment]
This is probably related to https://github.com/docker-library/docker/commit/ef1774baa091b633b95665177e518f5e07531bc7 (compose update) specifically :thinking:

(which means the answer is _probably_ somewhere in https://github.com/docker/compose/compare/v2.23.3...v2.24.0 :sweat_smile:)

**Comment by tianon** [comment]
Ah, specifically https://github.com/docker/compose/commit/fb3868ffafd49127e93e5bfd8aa2f12d1a27d5a5, thus https://github.com/docker/compose/pull/10939

**Comment by cjlarose** [comment]
Ah, makes sense. The version check is a little too aggressive

**Comment by cjlarose** [comment]
After tracking down the progress on `StartInterval` in https://github.com/moby/moby/issues/45897, it's clear that Docker 25.0 will indeed be the first version to properly support the new option.

For me, what was happening is that `start_interval` wasn't supported by `docker compose` prior to v2.24, but the old version would silently ignore it. With compose version 2.24, the new option is supported, but with throw an error if using a Docker Engine that doesn't support it.

I think this isn't technically a bug. It was really unexpected that upgrading `docker compose` broke my builds, but technically, I was trying to do something that wasn't supported anyway.

**Comment by tfausak** [comment]
``` sh
semaphore@semaphore-vm:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

semaphore@semaphore-vm:~$ docker compose version
Docker Compose version v2.24.1
```
