### ISSUE TITLE
dind-25.0.1 no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by iliuta** [docker-library/docker#475]
Hi, 

I'm trying to upgrade to the latest 25.0.1-dind image and I get the. following error:

no matching manifest for linux/amd64 in the manifest list entries

Am I missing something? Thank you.

**Comment by whalelines** [comment]
It is there now, https://hub.docker.com/layers/library/docker/25.0.1-dind/images/sha256-6863a098da35ab4bae6a3a80ab02997d93624ded0e263a14715dbe6e08260cd0?context=explore&tab=vulnerabilities . Not all variants of an image are published at the same time as the various builds complete at different times. Once the first os/arch variant is published the tag is available but it can take several hours for all os/arch variants to be published.
