### ISSUE TITLE
Docker fails to start inside VmWare

### ISSUE THREAD

**Issue by nssidhu** [docker-library/docker#476]
I am using VMware as Dev Environment for Personal works. It is not connected to any domain.

![Screenshot 2024-01-26 082252](https://github.com/docker-library/docker/assets/3267605/6797550b-f06b-48ea-a373-6ddb6206a84c)

I have even Reinstalled Docker but still running into issues.

How do i resolve this ?

**Comment by whalelines** [comment]
This repository contains the Dockerfiles for the [Docker Official Image `docker`](https://hub.docker.com/_/docker). You can find help for Docker Desktop at https://www.docker.com/support/ .
