### ISSUE TITLE
Docker image for amd64 and armv6 missing for 25.0.3-git

### ISSUE THREAD

**Issue by chickahoona** [docker-library/docker#478]
The docker tag 25.0.3-git currently has no manifest for armv6 and amd64.
As all the other tags (e.g. 25.0-git and 25-git) all have armv6 and amd64, I assume thats some kind of a bug or failed build pipeline?

The link to docker hub with the image with the missing 
https://hub.docker.com/_/docker/tags?page=1&name=25.0.3-git

The "correct" ones as reference:
https://hub.docker.com/_/docker/tags?page=1&name=25.0-git
https://hub.docker.com/_/docker/tags?page=1&name=25-git
https://hub.docker.com/_/docker/tags?page=1&name=git

**Comment by chickahoona** [comment]
Just saw that you just updated things to 25.0.3 a mere 8 hours ago, so I might have just been too fast with this issue. Feel free to close it without words if thats the case ;)

**Comment by tianon** [comment]
Yep, this was just that builds were still in progress. :+1:
