### ISSUE TITLE
Issue with missing DLL in runtime:4.8-windowsservercore-ltsc2022

### ISSUE THREAD

**Issue by nitinghaghada** [docker-library/docker#479]
I am using mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2022 as base image in my docker file to create custom image. After installing this custom image, I am frequently getting missing performance counter DLL error (Win32 error code 126) in the container in the event logs. See below error even log,

EventID            : 1023
MachineName        : XXXXXXXXX
Data               : {}
Index              : 4592
Category           : (0)
CategoryNumber     : 0
EntryType          : Error
Message            : Windows cannot load the extensible counter DLL "C:\Windows\System32\perfts.dll" (Win32 error code 126).
Source             : Microsoft-Windows-Perflib
ReplacementStrings : {C:\Windows\System32\perfts.dll, 126}
InstanceId         : 1023

When I looked for perfts.dll, I could not found it in c:\windows\system32 folder. 

Thanks & regards,
Nitin

**Comment by whalelines** [comment]
That image is not a Docker Official Image, not maintained in this repository, not maintained by Docker, and not served from Docker Hub. Perhaps reach out to Microsoft support for assistance?

**Comment by nitinghaghada** [comment]
Thanks David for quick reply. I will check with Microsoft. 

Regards,
Nitin
