### ISSUE TITLE
Docker Jellyfin /mnt/ windows drives

### ISSUE THREAD

**Issue by TTVAJSTYLES** [docker-library/docker#492]
Hi, i need help fixing a problem with my jellyfin local server. It’s probably easy for you guys but for a guy like me who started doing it is kinda difficult.

So my problem is that I run ubuntu server 20.04 on a Windows 11 using wsl. Docker+portainer and docker jellyfin are installed and working fine except for sharing my windows E and D drives using /mnt/e and /mnt/d. both didn’t work but once I changed my jellyfin docker container file from a bridge network to a host network, my /mnt/e windows 11 drive started working but still couldn’t get /mnt/e windows 11 drive to work some ppl say permissions but I don’t really know at this point.

Keep in mind when im on the terminal i can access both drives by using cd /mnt/e and cd /mnt/d on linux without any problems but jellyfin decided to find one drive after switching from a bridge network to a host network and completely ignored the other drive which is /mnt/d when trying to add it as a library.

The weird thing is that when I install jellyfin directly on the Ubuntu server without using docker image it works with both windows 11 drives when using /mnt/d and /mnt/e

But I really wanna be able to do it using docker
Portainer was installed on a fresh ubuntu 20 server using wsl so there is no users made but me AJ user and root

If anyone can help I would definitely appreciate it.

**Comment by whalelines** [comment]
Thank you for your interest in Docker. This repository is specifically for the `docker` official image, https://hub.docker.com/_/docker , and as such does not provide general support for running Docker images.

You can find Docker support options here: https://www.docker.com/support/

You can also join the Docker Community Slack and ask questions there: http://dockr.ly/comm-slack
