### ISSUE TITLE
Docker Requires "sudo" on Ubuntu version 22.04.1 LTS

### ISSUE THREAD

**Issue by novaTopFlex** [docker-library/docker#497]
Output from `uname -a`

    Linux ubuntu-macbookpro 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

I am not sure how the Linux distribution forces me to use `sudo` to activate Docker, and I have tested other distributions for which Docker does not require the `sudo` command. I am currently unsure how to pinpoint the error.

**Comment by whalelines** [comment]
This repository contains the source for the `docker` Docker Official Image, https://hub.docker.com/_/docker, and is not a general resource for running Docker.

You can ask for help in the [Docker Community Slack](https://dockercommunity.slack.com/). If you are not already a member of the Docker Community Slack, you can use [this link to join](http://dockr.ly/comm-slack). You can find more support options at [Docker Support](https://www.docker.com/support/), including documentation for [Docker Compose](https://docs.docker.com/compose/).

When you do ask for help, I would recommend including more detail about what you are trying to do, what commands you are running, and what errors are being reported.

In this case, perhaps you need to add your Ubuntu user to the `docker` group.

```sh
$ sudo usermod -a -G docker USER
```

Good luck!

**Comment by tianon** [comment]
See also https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user, especially the note about access to Docker being the same as root access on the host. :bow:
