### ISSUE TITLE
'overlay' not found

### ISSUE THREAD

**Issue by benjah1** [docker-library/docker#5]
I pull the docker:1.8, run it and get the following error.

```
/ # docker daemon
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: can't change directory to '/lib/modules': No such file or directory
, error: exit status 1
FATA[0000] Error starting daemon: Error initializing network controller: Error initializing bridge driver: Setup IP forwarding failed: open /proc/sys/net/ipv4/ip_forward: read-only file system
/ #
/ # uname -a
Linux 94d77ec93ce5 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 Linux
```

According to https://github.com/docker/docker/issues/14489, is it even possible to run docker on alpine?

**Comment by benjah1** [comment]
Need to docker run with flag --privileged. 

https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration 
https://blog.docker.com/2013/09/docker-can-now-run-within-docker/

**Comment by tianon** [comment]
Yes, if you want to run Docker within Docker, it requires the `--privileged` flag (which I believe the `docker` image documentation describes).

Additionally, if you want to use `overlay` you'll need to have that module available and loaded in your kernel on the host prior to launching your Docker-in-Docker container.

**Comment by benjah1** [comment]
This isn't really an issue, but a misunderstanding on usage. Close it now.
