### ISSUE TITLE
resources constraints on dind

### ISSUE THREAD

**Issue by kpavel** [docker-library/docker#51]
I created docker container with memory (-m) limit based on docker:1.8-dind while following the howto. When i started several [workload containers](https://github.com/progrium/docker-stress) i been able to use more memory than limited for parent container. Using "docker stats" on parent container doesn't reflect expected child container memory usage. Are resources constraints supported in docker in docker?

**Comment by tianon** [comment]
Nested resource constraints are only going to be supported to the level that the kernel and Docker support them.  To my knowledge, the kernel supports _some_ nested constraints, but Docker does not support nested constraints at all, so this is likely working as expected (and is not something this image can change). :+1:
