### ISSUE TITLE
Use "--driver docker-container"  network was timeout or reset peer when connect github or raw.github 

### ISSUE THREAD

**Issue by AnMokoto** [docker-library/docker#511]
# ISSUE
SAME AS https://github.com/moby/buildkit/issues/5299
1. Use "--driver docker-container"  network was timeout or reset peer when connect github.com or raw.githubusercontent.com
2. Use "--driver docker"  network was OK when connect github.com or raw.githubusercontent.com

# CODE
```yaml

script:
    - docker run --rm --privileged tonistiigi/binfmt --install all
    - docker context create ctx-$ARCH-$CI_PROJECT_ID
    - docker buildx create --name mybuilders --driver docker-container --use ctx-$ARCH-$CI_PROJECT_ID
    - |
      docker buildx build \
        --load \
        --builder mybuilders \
        --build-arg FLUTTER_VERSION=$FLUTTER_VERSION \
        --platform linux/${ARCH} \
        --cache-from type=registry,ref=${TAG_NAME} \
        --cache-to type=inline,mode=max \
        --tag ${TAG_NAME} \
        --network host \
        --file Dockerfile \
        --push .


```

# ENVIROMENT
```shell
$ docker info
Client:
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-76-generic
 Operating System: Alpine Linux v3.20 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.58GiB
 Name: runner-81syxtawp-project-104201-concurrent-0-bo3hvyq0
 ID: c05a2[24](https://gitlab.gz.cvte.cn/tv-infrastructure/cicd/hub.image/flutter/-/jobs/963034#L24)0-b373-4bc2-920c-da8622e70000
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  1[27](https://gitlab.gz.cvte.cn/tv-infrastructure/cicd/hub.image/flutter/-/jobs/963034#L27).0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

```dockerfile
FROM ubuntu:24.04
....
````

GITLAB-RUNNER: 17.02

tonistiigi/binfmt:latest
sha256:66e11bea77a5ea9d6f0fe79b57cd2b189b5d15b93a2bdb925be22949232e4e55

# CHECK LIST

## In Container:
- ✅ DNS
- ✅ ping & nslookup & dig
![image2024-9-4_14-39-6](https://github.com/user-attachments/assets/f0a5e7e5-9cab-4fbb-b0e8-bdec50aa3706)

- ❎ curl
![image](https://github.com/user-attachments/assets/38dc371d-bf11-4c28-bbe1-ffd8bca83c99)

## In Node:
- ✅ DNS
- ✅ ping & nslookup & dig
- ✅ curl

# TRY FIXING
## ❎ CURL -V
![image](https://github.com/user-attachments/assets/881d7a46-3b2d-49b0-b45e-91134271fe4a)

Install ca-certificates
```shell
apt-get -y update \
&& apt-get -y install ca-certificates wget \
&& mkdir -p /usr/share/ca-certificates/cacert.org \
&& wget -P /usr/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt \
&& update-ca-certificates
```
Refer：https://stackoverflow.com/questions/35821245/github-server-certificate-verification-failed/35824116#35824116

STILL ERROR.

## ❎ Custom Parameters
![image](https://github.com/user-attachments/assets/63340d53-b139-488a-840c-262c78b29281)

STILL ERROR.

##  ✅ RESET "--driver" DEFAULT
![image2024-9-4_17-43-20](https://github.com/user-attachments/assets/4b11ce2e-1750-4699-bada-ad7d10adb95a)

But, "--driver docker " not support multi-platforms.

![image](https://github.com/user-attachments/assets/e33bc4c1-9e9d-4e4b-b972-a00e32aa7474)

#

**Comment by tianon** [comment]
This repository contains the source for the `docker` Docker Official Image, https://hub.docker.com/_/docker, and is not a general resource for running Docker.

You can ask for help in the [Docker Community Slack](https://dockercommunity.slack.com/). If you are not already a member of the Docker Community Slack, you can use [this link to join](http://dockr.ly/comm-slack). You can find more support options at [Docker Support](https://www.docker.com/support/).

Good luck!

**Comment by AnMokoto** [comment]
> This repository contains the source for the `docker` Docker Official Image, https://hub.docker.com/_/docker, and is not a general resource for running Docker.
> 
> You can ask for help in the [Docker Community Slack](https://dockercommunity.slack.com/). If you are not already a member of the Docker Community Slack, you can use [this link to join](http://dockr.ly/comm-slack). You can find more support options at [Docker Support](https://www.docker.com/support/).
> 
> Good luck!

@tianon  Thx reply. i'll try it.  close this issue.
