### ISSUE TITLE
Digest Size Appears Unusually Large When Pushing Docker Image

### ISSUE THREAD

**Issue by v-49** [docker-library/docker#515]
When pushing a Docker image to a registry, the reported digest size appears excessively large. In my case, the local image is approximately 11GB, but the digest size shown in the push logs is reported as 24278GB. This seems unrealistic and could indicate a potential issue with the size unit or how the digest size is calculated and displayed.
![image](https://github.com/user-attachments/assets/bd54b95f-12e8-4694-b58e-3e1eb5e5827b)
display errors？How is this size calculated? What does it mean

**Comment by v-49** [comment]
anouther one :size: 368551GB   maybe cuz my dockerfile just one 'from'?

**Comment by tianon** [comment]
That _is_ unusually large. :thinking:

However, this repository contains the source for the `docker` Docker Official Image, https://hub.docker.com/_/docker, and is not a general resource for running Docker.

You can ask for help in the [Docker Community Slack](https://dockercommunity.slack.com/). If you are not already a member of the Docker Community Slack, you can use [this link to join](http://dockr.ly/comm-slack). You can find more support options at [Docker Support](https://www.docker.com/support/).

When you do ask for help, I would recommend including more detail about what you are trying to do, and a command which reproduces what you're seeing would be ideal.
