### ISSUE TITLE
Unable to change the group for the docker socket because the group does not exist

### ISSUE THREAD

**Issue by gunr2171** [docker-library/docker#55]
I'm running the docker dind image like this:

    docker run --rm -it --privileged docker:17.05.0-ce-dind

The very first line of the log is:

> could not change group /var/run/docker.sock to docker: group docker not found

And as such, the permissions of the docker socket are completely owned by `root`. Is this a bug or intentional?

I will be volume-ing the socket to other containers. Those containers run as non-root but are part of the `docker` group.

**Comment by yosifkit** [comment]
We have not had a docker group in the docker images.  Just give a group id to dind to use: `docker run --rm -it --privileged docker:17.05.0-ce-dind --group 1000`.  Then you'll guarantee that the id is whatever value you expect and can give the id to the other containers that use the socket.

**Comment by gunr2171** [comment]
Ah, I didn't know about that argument.

I did something similar: making my own image with dind as a base.

```
FROM docker:17.05.0-ce-dind
RUN addgroup -g 2999 docker
```

The command you give saves me from needing to make a whole new image. Thanks for that!
