### ISSUE TITLE
OpenSSL not included anymore

### ISSUE THREAD

**Issue by loicfrering** [docker-library/docker#56]
I have CI jobs based on this Docker official image and that are using openssl to generate `.htaccess` files before inclusion in images. Since 5a196cae40e2a0ab5050cf6d79b697e032352b24, the openssl package is not included anymore.

Is it removed on purpose (and I would be totally fine with this)? Or is it a regression you would rather not have?

Thanks!

**Comment by tianon** [comment]
Definitely was removed on purpose -- it's not needed by Docker at runtime, so it got pruned in the pursuit of leaner images. :sweat_smile:

**Comment by tianon** [comment]
(Especially since it's easy to add back, but impossible to actually remove if we include it unnecessarily.)

**Comment by loicfrering** [comment]
Sure, it definitely makes sense. Thanks for the feedback and for your work @tianon!
