### ISSUE TITLE
Add curl binary back to the image

### ISSUE THREAD

**Issue by tobias-kuendig** [docker-library/docker#57]
A few days ago my deployments started failing since the `curl` binary suddenly got removed from this image.

Any chance to add it back? I guess there are many people depending on it being installed...

**Comment by tianon** [comment]
This is similar to https://github.com/docker-library/docker/issues/56.

**Comment by tianon** [comment]
Closing, given that `curl` was removed intentionally (and shouldn't have been included by default in the first place).  It is unfortunate that this breaks some usages, but it isn't required by Docker itself, and it is pretty easy to fix (`RUN apk add --no-cache curl`). :+1: :disappointed:

**Comment by c24w** [comment]
Also, `wget` is available and can possibly be used where you need `curl`.

**Comment by fabiomontefuscolo** [comment]
curl is more powerful. You can setup a lot of headers and even override dns resolution. Also, curl is very user to glue systems, like Gitlab and Rancher and provide cool CD/CI solution. The curl removal probably breaks a lot of integrations like Gitlab+Rancher.

It is easy to extend docker-dind image and add `RUN apk add --no-cache curl`. But this makes harder to follow docker-dind development, releases and efforts.

Please, reconsider adding curl again. It's just a single ugly line that makes many lives beautiful.

**Comment by lloeki** [comment]
Today I got bitten by the issue, and obviously I immediately tried to replace `curl` with `wget`, yet the latter couldn't be arsed to download more than 16896 bytes for some reason. Adding an `apk add --no-cache curl` step worked, but, well, I don't see the point besides of being painful to users. Inquiry: is `wget` needed in any way by Docker?
