### ISSUE TITLE
docker swarm mode nginx not get client realip

### ISSUE THREAD

**Issue by dxawnw** [docker-library/docker#58]
in docker swarm mode ,run nginx container get the client ip is not real ip

for example 

# docker service ps nginx
![image](https://cloud.githubusercontent.com/assets/19405581/26484773/92aea306-4226-11e7-9068-126c13dcd81c.png)
![image](https://cloud.githubusercontent.com/assets/19405581/26484886/295c6630-4227-11e7-99d2-e9dc5c25fa96.png)
![image](https://cloud.githubusercontent.com/assets/19405581/26484865/0fcb1c48-4227-11e7-8132-31ad41b17247.png)
![image](https://cloud.githubusercontent.com/assets/19405581/26484899/4152f894-4227-11e7-8679-b2da1e7ecaf8.png)

everything get 10.255.0.2, no client ip 

but no swarm mode is ok

**Comment by yosifkit** [comment]
That is how swarm mode works. You'll need to file an issue with them to see if they have a way to forward the client IP in something like `X-Forwarded-For` so that Nginx could pickup the proper ip when using endpoint mode of `vip` (which is the default).
