### ISSUE TITLE
Versions previous to 1.7

### ISSUE THREAD

**Issue by mausch** [docker-library/docker#6]
There used to be Dockerfiles here for 1.6.0, 1.6.2 and even 1.5.0 , I wonder why they were removed?
Personally I need 1.6.2 , but shouldn't all versions be available instead of being upgraded in-place?

**Comment by yosifkit** [comment]
The Dockerfile is still in the git history: https://github.com/docker-library/docker/blob/522dd2fd70a9582b56441409682c213d189fce76/Dockerfile and the image is still available on the hub https://hub.docker.com/r/library/docker/tags/, but it is not part of the ["Supported Tags"](https://hub.docker.com/_/docker/#supported-tags-and-respective-dockerfile-links).

**Comment by yosifkit** [comment]
In case you are thinking about docker-in-docker, I would recommend looking at the post by Jérôme Petazzoni, "Tinkerer Extraordinaire": https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/.

**Comment by mausch** [comment]
My bad, didn't see that earlier versions are still available on docker hub.
Thanks!
