### ISSUE TITLE
publish arm32v7 image

### ISSUE THREAD

**Issue by bradrydzewski** [docker-library/docker#67]
I wanted to open this issue to track publishing an arm image to the official [arm32v7](https://hub.docker.com/u/arm32v7) organization in dockerhub. I see it is currently disabled and was hoping this issue could be used to provide status updates.

```
# Docker's "armhf" is ARMv7 (as of 2017-06-07, 17.06.0-ce-rc2)
#arm32v6 armhf armhf
```

If there is anything I can do to help please let me know.  I have a number of community members building and testing arm images that I am sure would be happy to lend a hand.

**Comment by gdeverlant** [comment]
There is also this place which seems to be official only for armhf https://hub.docker.com/u/armhf/

**Comment by tianon** [comment]
The main issue I haven't wrangled with yet is how to build an image targeting `arm32v7` which has to be `FROM` something that's `arm32v6`.

Additionally, the Alpine official image isn't actually _officially_ multiarch yet (still `amd64`-only ATM).  The image at `arm32v6/alpine` is something I've built from Alpine's official release tarballs, and is not (yet) maintained by the Alpine image maintainers.

@gdeverlant as you can see at the top of the description of images in each of those organizations, the (ambiguous) `armhf` organization has been split out into `arm32v7` and `arm32v6`, and the `aarch64` images have moved to `arm64v8`; see also https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by tianon** [comment]
For reference, the code in question which currently handles pulling the appropriate base image is at https://github.com/docker-library/oi-janky-groovy/blob/67ea7aa5a92633f7c3d6df95d7ff6b03379dd3d6/multiarch/vars.groovy#L230-L242.

**Comment by bradrydzewski** [comment]
FWIW I was able to modify the dockerfile and build for arm32v7 and arm64v8. I tested on scaleway servers and everything worked flawlessly.

I applied the below patch for arm32v7

```diff
--- Dockerfile	2017-07-19 11:55:20.000000000 -0400
+++ Dockerfile	2017-07-19 11:56:40.000000000 -0400
@@ -1,4 +1,4 @@
-FROM alpine:3.6
+FROM arm32v7/alpine:3.6
 
 RUN apk add --no-cache \
 		ca-certificates
@@ -22,6 +22,7 @@
 # this "case" statement is generated via "update.sh"
 	apkArch="$(apk --print-arch)"; \
 	case "$apkArch" in \
+                armhf) dockerArch='armhf' ;; \
 		x86_64) dockerArch='x86_64' ;; \
 		s390x) dockerArch='s390x' ;; \
 		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
```

I applied the below patch for arm64v8. Note the static binaries are not yet available for aarch64 so I had to build from source and publish to s3 manually.

```diff
--- Dockerfile	2017-07-19 11:55:20.000000000 -0400
+++ Dockerfile.aarch64	2017-07-19 11:59:48.000000000 -0400
@@ -1,4 +1,4 @@
-FROM alpine:3.6
+FROM arm64v8/alpine:3.6
 
 RUN apk add --no-cache \
 		ca-certificates
@@ -22,12 +22,13 @@
 # this "case" statement is generated via "update.sh"
 	apkArch="$(apk --print-arch)"; \
 	case "$apkArch" in \
+                aarch64) dockerArch='aarch64' ;; \
 		x86_64) dockerArch='x86_64' ;; \
 		s390x) dockerArch='s390x' ;; \
 		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
 	esac; \
 	\
-	if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+	if ! curl -fL -o docker.tgz "https://s3.amazonaws.com/downloads.drone.io/docker-17.05.0-ce.tgz"; then \
 		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
 		exit 1; \
 	fi; \
```

I am not sure what the status is of official static binaries for aarch64. @vielmetti you mentioned in https://github.com/docker-library/docker/issues/41 that you are working with the docker team to provide an aarch64 build server for the purpose of publishing an official aarch64 binary? Any updates to share? cc @mmlb

> The main issue I haven't wrangled with yet is how to build an image targeting arm32v7 which has to be FROM something that's arm32v6.

I wish I could help out more here. I am not yet familiar enough with the groovy language or the overall docker library build process to suggest a workaround :( 

But if there is anything I _can_ help with please let me know

**Comment by klud1** [comment]
I'm maintaining an unofficial image for armhf using the [multiarch/alpine](https://hub.docker.com/r/multiarch/alpine/) image (this contains the qemu binary), here's the repo [github.com/klud1/docker-in-docker-arm](https://github.com/klud1/docker-in-docker-arm) and the images [klud/docker](https://hub.docker.com/r/klud/docker/), [klud/dind](https://hub.docker.com/r/klud/dind/)

**Comment by klud1** [comment]
Btw, is there a binary available for 17.03.2-ce?

**Comment by vielmetti** [comment]
@bradrydzewski a useful tracking item is https://github.com/linuxkit/linuxkit/issues/1377 for the issue of Linuxkit on ARM64. If I recall correctly, one ongoing gating item for Docker on ARM64 official builds has been the availability of a supported Go on ARM64 official build, and that is destined for Go 1.9 per the successful close of https://github.com/golang/go/issues/19082 .

**Comment by tianon** [comment]
This was fixed via https://github.com/docker-library/docker/commit/6001c15038b05149a83dcc17e1bbeedc92979f6d :+1:
