### ISSUE TITLE
cURL does not work (anymore)

### ISSUE THREAD

**Issue by sameersbn** [docker-library/docker#72]
cURL installed in `docker:17.06.0-ce-git` release does not seem to work. 

```console
# docker run -it --rm docker:17.06.0-ce-git sh -c 'apk add --no-cache curl && curl -vL https://www.google.com'
Unable to find image 'docker:17.06.0-ce-git' locally
17.06.0-ce-git: Pulling from library/docker
88286f41530e: Pull complete 
61bf6059e353: Pull complete 
0b539e28e9a6: Pull complete 
ad3af5fe81b0: Pull complete 
ec33fee374b5: Pull complete 
Digest: sha256:b5ff49006c6d5f6a4962953c6cafe3949c43f342c1eea84c12b76a9f5f4a1777
Status: Downloaded newer image for docker:17.06.0-ce-git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/1) Installing curl (7.55.0-r0)
Executing busybox-1.26.2-r5.trigger
OK: 28 MiB in 20 packages
curl: (48) An unknown option was passed in to libcurl
```

The issue seems to be due to the mismatch between `libcurl` and `curl` package versions, Upgrading `libcurl` fixes the issue (something that `apk` should automatically do).

```console
# docker run -it --rm docker:17.06.0-ce-git sh -c 'apk upgrade --no-cache libcurl && apk add --no-cache curl && curl -vL https://www.google.com'
```

Since libcurl is not required by Docker itself, you should probably remove it and any other unused dependencies.

**Comment by tianon** [comment]
Sorry for the delay!

We only explicit install `curl` (or `libcurl`) in one place:

https://github.com/docker-library/docker/blob/4782798943949422d73ebc94407d277424afa58b/18.06/Dockerfile#L19-L26

It is then subsequently removed: (and I've just gone and verified that both `curl` and `libcurl` are removed by this line)

https://github.com/docker-library/docker/blob/4782798943949422d73ebc94407d277424afa58b/18.06/Dockerfile#L51

So, all I can figure is that one of `git` or `openssh-client` is pulling in `libcurl`:

https://github.com/docker-library/docker/blob/4782798943949422d73ebc94407d277424afa58b/18.06/git/Dockerfile#L3-L5

I'm not sure what to do from here.  Part of me wants to simply deprecate the `git` variant entirely, given that the value it provides is pretty minimal (as you can see, its only addition is two packages above the base).

Given that it works on the latest 18.06 release, I'm also inclined to close this as a fluke.
