### ISSUE TITLE
Version Support Policy

### ISSUE THREAD

**Issue by WhisperingChaos** [docker-library/docker#73]
Can someone please direct me to older versions of DIND, like version 1.2?  I use DIND to test compatibility with newer/older versions of Docker/Moby and I can't find older versions prior to 17.* on Docker Hub.

Also, is there a stated support policy on maintaining prior versions of DIND?

Thanks!

**Comment by yosifkit** [comment]
Though they are not listed on the Docker Hub UI, they are available to see through the api and `docker pull docker:[version]-dind` will work on all old images from `1.0` onward.  Officially we only support those listed on the Hub description, but keep all versions prior.

**Comment by WhisperingChaos** [comment]
Thanks for your answer and rapid reply!
