### ISSUE TITLE
docker:17.09 (without trailing '.0') tag missing

### ISSUE THREAD

**Issue by thaJeztah** [docker-library/docker#80]
I noticed, unlike for other releases, there's no `docker:17.09` tag on Docker Hub. Perhaps this is because there's no GA release yet for 17.09, but could also be it was missed :smile:

ping @tianon

**Comment by yosifkit** [comment]
Spoke with @tianon; he says yes that is on purpose since there is no GA release.  He also thinks that these should also not exist for RC versions: `17.09.0-ce 17.09.0`.

**Comment by thaJeztah** [comment]
Thanks for checking!
