### ISSUE TITLE
cURL not linking properly in docker:17.09.0-git

### ISSUE THREAD

**Issue by dr-impossible** [docker-library/docker#83]
If I try to run the following commands in the image `docker:17.09.0-git` (or build a docker image based on this image):
```
apk add --no-cache curl
curl
```
I'll get the following error:
```
Error relocating /usr/bin/curl: curl_mime_data_cb: symbol not found
Error relocating /usr/bin/curl: curl_mime_name: symbol not found
Error relocating /usr/bin/curl: curl_mime_encoder: symbol not found
Error relocating /usr/bin/curl: curl_mime_init: symbol not found
Error relocating /usr/bin/curl: curl_mime_headers: symbol not found
Error relocating /usr/bin/curl: curl_mime_filedata: symbol not found
Error relocating /usr/bin/curl: curl_mime_free: symbol not found
Error relocating /usr/bin/curl: curl_mime_subparts: symbol not found
Error relocating /usr/bin/curl: curl_mime_type: symbol not found
Error relocating /usr/bin/curl: curl_mime_addpart: symbol not found
Error relocating /usr/bin/curl: curl_mime_filename: symbol not found
Error relocating /usr/bin/curl: curl_mime_data: symbol not found
```

If I do the same using the image `docker:17.09`, curl runs without any issue, even if I also install `git` and `openssh-client` first

**Comment by tianon** [comment]
Whoa, I can reproduce -- that's a bizarre one! :confused:

I wonder if we managed to get a "butterfly" on the build server which caused `libcurl` to be messed up.  I'll go see what I can do to force that to rebuild!

**Comment by tianon** [comment]
The image is rebuilt and repushed, and appears to be working properly now. :+1:
```console
$ docker pull docker:17.09-git
17.09-git: Pulling from library/docker
88286f41530e: Already exists 
c401a59c6e87: Already exists 
f605b94abcd1: Already exists 
9aa28679c902: Already exists 
7b78ba896fc6: Pull complete 
Digest: sha256:0d53276d97ffd1348cd1c9d56f3d1497dbd890a2060aa05fd8e8ff67a412b03d
Status: Downloaded newer image for docker:17.09-git
$ docker run -it --rm docker:17.09-git
/ # apk add --no-cache curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/1) Installing curl (7.56.0-r0)
Executing busybox-1.26.2-r5.trigger
OK: 28 MiB in 20 packages
/ # curl
curl: try 'curl --help' or 'curl --manual' for more information
/ # 
```

**Comment by allanbreyes** [comment]
I'm also seeing this problem on `docker:17.05.0-ce-git`. Perhaps this may have made it into multiple builds?

**Comment by tianon** [comment]
@allanbreyes it's certainly possible, although I'm hesitant to go fix it for an unsupported older version :disappointed: 

Any particular reason you need 17.05 specifically?

**Comment by allanbreyes** [comment]
Thanks for the response! I just upgraded for a fix, but I thought it might be a signal that other builds may have this problem as well.

**Comment by jlambert121** [comment]
I am having this on 17.09.1-ce-mac42 build 21090 as well.

**Comment by sameersbn** [comment]
seeing this with `docker:17.06.0-ce-git` 

ref: https://circleci.com/gh/bitnami/bitnami-docker-codiad/55

**Comment by sameersbn** [comment]
update: upgrading libcurl (or all system packages) fixes the issue

**Comment by so0k** [comment]
to upgrade libcurl package or the full system follow this guide [Alpine Package Manager -
 upgrading a running system](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Upgrade_a_Running_System)

**Comment by janhartigan** [comment]
Might help someone else, but the exact lines I added before my apk install was:

```
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
  apk update && \
  apk upgrade && \
  apk --no-cache add \
    bash \
    ....
```
