### ISSUE TITLE
usage of eval instead of exec in docker-entrypoint.sh

### ISSUE THREAD

**Issue by Rambrant** [docker-library/docker#9]
I tried to use the container from maven, more precisely the  plugin "exec-maven-plugin". The problem is the way the plugin treats parameters. As long as you just call simple docker commands everything looks good but as soon as you get a bit more complicated you are greeted with a 'not found' message from exec...

I exchanged exec and put eval there instead and everything seemed to work much better. Is thera any good reason to use exec or is it a good idea to switch to eval?

[docker-entrypoint.txt](https://github.com/docker-library/docker/files/197979/docker-entrypoint.txt)

PS I renamed the shell script to txt to get it uploaded :-)

**Comment by tianon** [comment]
I think this might be filed against the wrong repository -- this is the `docker` image (https://hub.docker.com/_/docker/).

Regarding `eval` vs `exec`, they do very different things:
```console
$ help eval
eval: eval [arg ...]
    Execute arguments as a shell command.
    
    Combine ARGs into a single string, use the result as input to the shell,
    and execute the resulting commands.
    
    Exit Status:
    Returns exit status of command or success if command is null.
$ help exec
exec: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
    Replace the shell with the given command.
...
```

Somewhat clearer, `exec` replaces our current shell session with whatever it is we pass to it (so our shell is no longer resident -- thus ending a script with something like `exec "$@"` and then running that script with `some-command` as an argument will end up running `some-command` and the shell process will be completely gone).

On the other hand, `eval` parses its argument as a shell script, invokes it, and returns.  Thus, things like `eval 'echo $PATH'` will print out the value of the `PATH` environment variable.
